### ISSUE TITLE
Scalaing ranch across server

### ISSUE THREAD

**Issue by FGRibreau** [ninenines/ranch#105]
Hello @Essen,

A friend of mine just introduced me to ranch, it seems to be a good first step resolving my use-case.

Let me add a little context. My use case is as follow: I have currently a server than needs to handle a growing number of persistent TCP connections. 
Is ranch able to scale across servers? Do you know any projects/patterns (not necessarily in erlang) that is able to so?

The kind of pattern I'm looking for in ranch would be to have a kind of "router" that can forward a client to the right ranch server that maintains the TCP connection. Is it possible with ranch?

**Comment by essen** [comment]
Ranch just manages connections at the application level.

If you need more than one server, then you need to have a lower level mechanism that would route connections to one or the other server. This can be done with various network equipment, software firewalls in a gateway server and others. It's the same as you would for nginx or any other server.

**Comment by essen** [comment]
Hope I answered your question. Closing, thanks!
