### ISSUE TITLE
Created two workers and listeners on a single POST query

### ISSUE THREAD

**Issue by Slavenin** [ninenines/ranch#106]
Hello!
I`am use ranch for controlling by post request in socket. If i send request from php using curl, i see run two listener (-behaviour(ranch_protocol)) in observer and two worker by one on listener. I created test repo https://github.com/Slavenin/ranch_bug for repeat this bug. If i send request from php using socket module, repeated no.

**Comment by essen** [comment]
There are two sockets opened because your PHP script calls curl_exec twice.

**Comment by Slavenin** [comment]
How could I not notice? .. I do not understand ... Thank you! :+1:
