### ISSUE TITLE
TCP keepalive

### ISSUE THREAD

**Issue by gbour** [ninenines/ranch#108]
Hello Loïc,

Any reason tcp keepalive are not allowed in ranch_tcp ?

**Comment by essen** [comment]
No. Patch welcome.

**Comment by gbour** [comment]
a quick ping to remind you the patch is available ;)

**Comment by essen** [comment]
Done in 0d5d855da3d0b2d508fae4258b125a3a5ab7b306 along with many more options, and including documentation.

**Comment by gbour** [comment]
thanks
