### ISSUE TITLE
Ranch 2

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#111]
I believe these are the main improvements that should be brought to Ranch 2:
- Merge acceptors with connection supervisor: https://github.com/ninenines/ranch/issues/110
- Better ssl_accept support (I will have to dig up suggestions, I believe @asabil had something good in mind.)
- Graceful and brutal shutdown of connections.
- Restart a listener with new options without service interruption.
- Handle cases where matching on the socket is not possible: https://github.com/ninenines/cowboy/pull/912/files#r44168355
- Release upgrades

**Comment by juhlig** [comment]
What OTP Versions would you be targeting with Ranch 2? As you mentioned in issue #126 the function required is in OTP 19, but by including it in Ranch we would drop support for OTP Versions below 19.

**Comment by essen** [comment]
I would most likely test on 19+ but don't plan to dramatically break things. If it's just a few new functions requiring 19+ then people can probably continue to use it.

**Comment by juhlig** [comment]
Ok, in that case, how should I approch this? Just an unchecked call like ssl:get_stats(...) and simply let it crash there if that function does not exist in ssl (eg, OTP<19), or check if function exists and raise a "custom" error?

**Comment by essen** [comment]
Just an unchecked call is fine.

**Comment by juhlig** [comment]
Ok, thanks, I will get to it :)

**Comment by essen** [comment]
Closing because it's covered by other tickets.
