### ISSUE TITLE
Provide access for setting options in ranch_ssl:accept_ack/2

### ISSUE THREAD

**Issue by ahf** [ninenines/ranch#112]
I needed a way of dynamically changing the SSL certificate for a listener WITHOUT having to restart the listener again.

I did the following "hack" where I wrapped `ranch_ssl` in my own module and switched to use `ssl_accept/3` instead of `ssl_accept/2` in `accept_ack/2`.

It would be nice to be able to set these options directly from `ranch_ssl` instead of having to wrap the module.

Maybe this also could mean that `ranch_ssl` doesn't HAVE TO require a `cert` og `certfile` to be set during initialisation.

https://gist.github.com/ahf/bfb80dbf2801d78b7826#file-gistfile1-erl-L52-L78

**Comment by essen** [comment]
You can suspend a listener, update its configuration and resume it in the most recent commit. This leaves existing connection open. Please try it! Thanks.
