### ISSUE TITLE
Send Timeout not work

### ISSUE THREAD

**Issue by Alex-query** [ninenines/ranch#116]
My settings
ranch:start_listener(tcp_reverse, 10,
		ranch_tcp, [{port, 5555},{active, true}, {packet, 0}, {keepalive,
        true}, {reuseaddr, true},{nodelay, true},{send_timeout, 360000}, {send_timeout_close, true},{backlog, 4096}], reverse_protocol, []),

As if I did not change vakue send_timeout , tcp_error still comes to only 16 minutes
{tcp_error,#Port<0.420>,etimedout}

Please tell me how to set up, so I just learned about the loss of Internet connection at the client

**Comment by essen** [comment]
Should be just like this. Not sure what's the intended result though?

**Comment by Alex-query** [comment]
I want known, when device switched off.
I have controllers , that communicate via sockets to the server. I must to know when the device lost connection. 
http://joxi.ru/zAN0MP3uWdzMm9.jpg
My task immediately know when the controller is switched off.

**Comment by essen** [comment]
There is no way to reliably know when the connection is down with TCP. There are ways to improve detection, but you will need application-level timeout handling (using ping/pong for example) for reliability.

**Comment by Alex-query** [comment]
I thought about it, but still hoped that through the tcp will.
Thank you for the clarification ! Yes and ranch, cowboy, too, you are making a very cool projects !

**Comment by essen** [comment]
Thanks! Closing then. :-)
