### ISSUE TITLE
Remove 'socket' option

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#123]
If the socket closes, all bets are off. This is too dangerous.

Better if we explain to users how to write a simple transport module that can do the same, except in the listen callback. Then when we call listen again after the first one closes we can open a new socket and everything is good.

**Comment by rlipscombe** [comment]
We talked about this in https://twitter.com/rogerlipscombe/status/633312028413829120. I've since updated our code to use a custom transport. That is: it wraps `ranch_ssl`, except for `listen/1`, where we do it ourselves. So: no complaints from me if you do this.

**Comment by essen** [comment]
Good to hear, and should be more solid as a result. :-)

Thanks for the heads up!

**Comment by essen** [comment]
It was removed a few days ago.
