### ISSUE TITLE
max_connections parameter is documented incorrectly

### ISSUE THREAD

**Issue by doubleyou** [ninenines/ranch#128]
The following section suggests that `max_connections` is supposed to be passed using `TransportOpts`: https://github.com/ninenines/ranch/blob/master/doc/src/guide/listeners.asciidoc#limiting-the-number-of-concurrent-connections

However, it's actually being passed from `ProtOpts`: https://github.com/ninenines/ranch/blob/master/src/ranch_listener_sup.erl#L25

Looks like there are multiple things we can improve/fix:
1. The mentioned inconsistency. Intuitively, it feels like `ProtoOpts` is a better place to go, but maybe not (see point 3).
2. Lack of documentation about possible options in the manual. There's a note about the `opt()` type, but it's not clear from the manual which parameter is supposed to use these options.
3. Technically, it looks like things like `max_connections` is not exactly related to either `TransportOpts` or `ProtoOpts`, it's rather another subset that should be called `RanchOpts` or something. However, I guess this approach will hurt backwards compatibility.

I'm totally down for fixing the whole thing and filing a pull request, as long as there's a clean agreement on what to do here.

Thanks!

**Comment by essen** [comment]
I believe this is the line you are looking for? There's no mistake there.

https://github.com/ninenines/ranch/blob/master/src/ranch_listener_sup.erl#L24

I don't disagree with this being Ranch specific options. Perhaps in Ranch 2 we could make NbAcceptors be a set of options instead, and put those there.

**Comment by doubleyou** [comment]
Oh, sorry, my bad. It's really in transport options.

**Comment by doubleyou** [comment]
Then I don't really understand why starting a server with `max_connections` set to 1 still allows me to open more than one connection.

**Comment by doubleyou** [comment]
Like, I run multiple telnet sessions to the host and all of them are working fine.

**Comment by doubleyou** [comment]
I'll try to work on a minimal case to show, since generic feedback isn't really helpful here.

**Comment by doubleyou** [comment]
Okay, so here's the simplest example I could come up with:

1. Modify the `tcp_echo` example in the ranch repo by adding `{max_connections, 1}`.
2. Build and start the example.
3. Run `telnet localhost 5555` in two or more separate consoles.

The result is – all telnet sessions open immediately, but only one of them is responding to any requests.

This seems to be in line with the way tests work: https://github.com/ninenines/ranch/blob/master/test/acceptor_SUITE.erl#L511. We successfully open as many connections as we want but only some of them become active.

This behavior is a bit misleading, because intuitively it feels (due to the name, `max_connections`) like new connections should be refused (guess on the TCP level), not accepted and suspended until some "room" in connection pool frees up.

**Comment by doubleyou** [comment]
I'm not really sure about the way we should behave here. There definitely is value in the current behavior, but an ability to refuse connections on the TCP level would be nice too.

In principle, it's possible to just make another parameter that would be actually limiting the amount of accepted connections. What do you think?

And this deserves some additional explanation in the docs, anyhow. :)

**Comment by essen** [comment]
This is the maximum number of *connections*. The others, which are not connected yet, are sitting in the TCP *backlog*. There's an option for that too.

**Comment by doubleyou** [comment]
Hmm, looks like it's `telnet`'s behavior that confused me: it says "connected" before the connection is actually accepted.

So, technically, the amount of connections we can create before new connections start getting refused is `max_connections` + `backlog`? Or `max_connections` + `n_acceptors` + `backlog`?

Thanks for being patient about my mistakes. Do you think there's value in explaining this stuff in more details somewhere in the documentation? I could make a draft and file a pull request.

**Comment by essen** [comment]
max_connections + backlog.

The number of acceptors is unrelated, it's the number of processes that do the work of accepting connections.

This could be useful in the documentation. PR welcome of course!

**Comment by doubleyou** [comment]
Hmm, so I did more digging and minimized this to the following test case: https://github.com/doubleyou/ranch/tree/n_acceptors_experiment/examples/tcp_n_acceptors

From that experiment, it seems like `n_acceptors` does affect the maximum amount of established connections :(

Also, while looking into the way backlog works, I stumbled upon this one: http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html. This is exactly what confused me – client connections get into half-open state, due to the way Linux TCP implementation works.

**Comment by essen** [comment]
You are just running into the fact that max_connections is a soft limit. If you do tests with max of 1, then yes, you will need to reach the number of acceptors to stop them from accepting connections, and one of them will start accepting again only once the number of connections goes below 1.

In practice though you generally accept a lot more connections than you have acceptors so there's little discrepancy.

**Comment by doubleyou** [comment]
Doesn't that mean that the actual number of connections would be something around `max_connections` + `backlog` + `n_acceptors` then, at least in case of a churn of connections?

I agree with what you're saying, for the most intuitive setup (big or infinite `max_connections`, significantly small backlog, significantly small amount of acceptors) the deviation will be small enough not to care about it. However, sometimes they may be set differently, due to some circumstances or by mistake.

As an example, we had approximately the following setup: 'n_acceptors = 1000`, `backlog = 20000`, `max_connections = infinity`. The backlog and acceptor pool size were supposed to handle a churn of connections, which they did. However, when we recognized the need of limiting the amount of connections fairly hardly (2-3k) due to application-specific limits, it was very confusing that just reducing `max_connections` (and then backlog size too) didn't really give the expected result. Just because `n_acceptors` and `max_connections` were comparable, and I didn't bother reducing `n_acceptors`.

Maybe my situation is somewhat unique and nobody else will run into the same problem ever again, I don't know :)

**Comment by essen** [comment]
The soft limit is documented, its exact effects are not (because that can change based on implementation). So yes, it's probably what you say, but it's subject to change (in Ranch 2 the limit will become a hard limit but it will be per-acceptor rather than per-listener; however I will still document it as a soft limit for now).

Running 1000 acceptors is probably crazy, by the way. In my tests I found that there's a middle ground value at which point benefits stop and things become worse. For example on my machine 100 is better than 10, but 100 is also better than 1000.

The backlog will not have any impact on the maximum amount of connections (the one reported by Ranch). The amount reported by the OS, well, I can't really do anything about that. :-) But perhaps this could be added to the documentation.

**Comment by essen** [comment]
Improved the guide in my local copy. Closing, thanks!
