### ISSUE TITLE
Re: Custom supervisor & Ranch

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [ninenines/ranch#132]
From http://ninenines.eu/res/erlanger-preview.pdf

"Indeed, if we have ten acceptors that are also supervisor, then we don’t have the bottleneck that we had when there was ten acceptors for one supervisor."

Brilliant. Can't wait for your book to drop.

Are you planning to include any of this in a new or custom version of Ranch?

**Comment by essen** [comment]
Ranch 2 (#111), in particular #110. I started this a while back but unfortunately had to do more urgent things, including a Ranch 1.2 release. :-) I'm aiming for this to be done in a month or two.

**Comment by CharlesOkwuagwu** [comment]
Like i said, brilliant.
