### ISSUE TITLE
Update Hex Package

### ISSUE THREAD

**Issue by sds88** [ninenines/ranch#136]
The most recent version of Ranch available on Hex is 1.2.0 which includes an erlang.mk that isn't compatible with Windows.  I manually updated the erlang.mk file and was able to compile.  I see you guys already updated the erlang.mk file in the master branch with commit 666e539 in mid december, it would be great to get a updated hex version that includes that change.

**Comment by essen** [comment]
I don't maintain the hex package.

**Comment by sds88** [comment]
Oh, sorry.  Do you know who does?

**Comment by essen** [comment]
I think there's a repo in the hex github for community maintained packages.
