### ISSUE TITLE
Race condition with gen_server protocol

### ISSUE THREAD

**Issue by stolen** [ninenines/ranch#137]
[Documentation](http://ninenines.eu/docs/en/ranch/HEAD/guide/protocols/#using_gen_server) says you can use a zero timeout in `init/1` when protocol is based on a `gen_server`.

But the example code fails to function properly sometimes.
If `handle_info` does not crash on unknown message, the protocol may stall between `init/1` and the other logic.

[Proof](https://gist.github.com/stolen/c3eb9dcdcc7060bb8efc) (runs on Linux).

Fix suggestion:
- Add `{ack_module, AckModule}` ranch option which defaults to `ranch`.
- Put the `{shoot, ...}` message sending into `ranch:send_ack(Ref, Transport, Socket, AckTimeout)`
- Require custom ack module to call `Transport:accept_ack(Socket, AckTimeout)` when ack is received.

This will allow user to use `gen_server:cast`, `gen_fsm:send_event` or anything else for acking socket ownership change. No need for a timeout hack, no need for `enter_loop`.

**Comment by essen** [comment]
To be honest I should probably just remove this part of the documentation. The only right way to do it is enter_loop. I have no intention to support any other hackish way.

**Comment by stolen** [comment]
I think `enter loop` is as hacky as timeout. It requires user to understand internals of standard behaviours (which should "just work") and use them in very special way. Not beginner-friendly.

**Comment by essen** [comment]
Timeout is subject to race conditions, enter_loop is not.

**Comment by stolen** [comment]
True.
May there be any other way? Simple to use but robust?

**Comment by essen** [comment]
Well enter_loop is there because there is no other way. :-)

**Comment by stolen** [comment]
So, `AckModule` stuff is not a way at all?

**Comment by essen** [comment]
There's more problems, one of them being that init is done as part of gen_server:start_link and there's a timeout for the starting of the process and the ack can take more than that with SSL; no problem with proc_lib:spawn_link (or start_link if you ack before).

**Comment by stolen** [comment]
I've read some OTP code and found that it's possible to make self a controlling process:
  * `gen_tcp:controlling_process` after some checks calls `erlang:port_connect/2` and then unlinks the old owner from port. It's possible to call `erlang:port_connect/2` from a protocol worker.
  * `ssl:controlling_process` does not require caller to be current controlling process.

So why not change ownership ack mechanism to not require non-obvious protocol start sequence?
My suggestion:
  * acceptor does not make conns_sup a controlling process
  * `accept_ack` makes the caller a controlling process
  * `accept_ack` sends a message, e,g, `{control_taken, Socket, Worker}` to the acceptor (previous controlling process)
  * acceptor waits for `control_taken` message, then resumes operation

This would simplify couple of things while keeping the API backwards-compatible.

**Comment by essen** [comment]
``` erlang
9> {ok, S} = gen_tcp:connect("google.com", 80, []).                        
{ok,#Port<0.570>}
10> spawn(fun() -> io:format("~p~n", [gen_tcp:controlling_process(S, self())]) end).
{error,not_owner}
<0.51.0>
```

**Comment by stolen** [comment]
```erlang
63> f(S), {ok, S} = gen_tcp:connect("google.com", 80, [{active, false}]).
{ok,#Port<0.598>}
64> spawn(fun() -> io:format("~p~n", [erlang:port_connect(S, self())]), receive stop -> ok end end).
true
<0.112.0>
65> erlang:port_info(S, connected).
{connected,<0.112.0>}
```

**Comment by essen** [comment]
Ahah, yeah but I'm not going to do that.

**Comment by essen** [comment]
I have remove the timeout method, and improve the enter_loop method so that it doesn't break the specs. I am also updating the tcp_reverse example. This is on my local copy but will be pushed soon. Closing, thanks!
