### ISSUE TITLE
need to handle the sleepers and num_of_children when changing the controlling process of `Socket` to `ProtocolPid`

### ISSUE THREAD

**Issue by lerencao** [ninenines/ranch#140]
In the following case(shoot...),

```
case Transport:controlling_process(Socket, ProtocolPid) of
  ok ->
    %%%......
  {error, _} ->
    Transport:close(Socket),
    exit(SupPid, kill),
    loop(State, CurConns, NbChildren, Sleepers)
end
```

After killing the child process(the `{'EXIT', child, reason}` message will comes to conn_sup), caller of the `start_protocol` still wait for the `receive SupPid -> ok end` message, and because the caller is not in the sleepers list, there is no way for it to be awake again.

**Comment by essen** [comment]
Good find. It should have a `To ! self(),` line.

**Comment by lerencao** [comment]
@essen That's not enough. What's about the exit message from the killed child? Dealing with the {'EXIT', child, reason} message will disrupt the `CurConns` and `NbChildren`.

```
    {'EXIT', Pid, Reason} ->
      report_error(Ref, Protocol, Pid, Reason),
      erase(Pid),
      [To|Sleepers2] = Sleepers,
      To ! self(),
      loop(State, CurConns - 1, NbChildren - 1, Sleepers2);
```

**Comment by essen** [comment]
True. I guess adding them to the sleepers list would have the intended effect. Need a good test first.

**Comment by essen** [comment]
The current code should handle a stray message properly (if it is unknown it is just ignored). Therefore we can just resume the acceptor and be done with it.

I'm not sure how to properly test this so I won't add a test for the time being.

**Comment by essen** [comment]
Fixed in master. Thanks!
