### ISSUE TITLE
The default listener options is not really default

### ISSUE THREAD

**Issue by lerencao** [ninenines/ranch#141]
> By default the socket will be set to return `binary` data, with the options `{active, false}`, `{packet, raw}`, `{reuseaddr, true}` set. These values can’t be overriden when starting the listener.

In fact, it can be.

The bug caused by the line of code(in `ranch:filter_options`): 
```
lists:foldl(fun merge_options/2, DefaultOptions, AllowedOptions)
``` 
 I think you had a typo here. Swap the position of `DefaultOptions` and `AllowedOptions` can fix this.(I'd like to give a PR, but I use 2-space instead of TAB, got format problem in emacs when saving files, so if just drop it here)

**Comment by essen** [comment]
I'm not sure I understand, is it that difficult to set indentation options in emacs? Do you not have an other text editor (surely for a simple change like this, any would do).

Anyway do you have a clear example of a case where it doesn't work? Something I could run in the shell? Those options are removed before the code you quote, with a warning printed.

**Comment by lerencao** [comment]
Oh, my bad I forgot the allowed_keys. That's embarrassing...
However, when merging options, using `DefaultOptions` as the iterator  can make more sense, after all, the default options should not be overridden, instead, use the default options to override user options passed. (As the user options has been filtered, there is nothing to override at all).

Never mind, forget this issue and the indentation...

**Comment by essen** [comment]
Closing then, thanks. :-)
