### ISSUE TITLE
Document that Ranch listeners are themselves supervisors, not workers

### ISSUE THREAD

**Issue by rightfold** [ninenines/ranch#142]
I could not find in the documentation how to supervise Ranch listeners themselves. It appears from the source code that Ranch listeners are supervisors, and so when using a Ranch listener in a child spec, `type` should be set to `supervisor`, not `worker`. I think this should be documented. I think it also should be documented what `modules` should be set to.

Unless Ranch was not designed to be supervised at all?

**Comment by essen** [comment]
There's a ranch:child_spec function that gives the exact child spec to use when embedding in your application. This is documented, it has a whole chapter about it: http://ninenines.eu/docs/en/ranch/1.2/guide/embedded/

Thanks!

**Comment by rightfold** [comment]
Ah, I see. I didn't know that. Thanks. :)
