### ISSUE TITLE
How determine that all data readed

### ISSUE THREAD

**Issue by postHawk** [ninenines/ranch#150]
Hi!
How i can determine that all data from soket is read? I have POST request with big data. I use example from https://github.com/ninenines/ranch/blob/master/examples/tcp_reverse/src/reverse_protocol.erl .
My listener:
```erlang
handle_info({?PROTOCOL, Socket, Data}, State=#state{socket=Socket, transport=Transport}) ->
	?DBG(byte_size(Rest)),
	{noreply, State};
```
infinitely wait new data, even when data is end. There is a way determine that all data from soket is read besides timeout?
Tnx!

**Comment by essen** [comment]
Protocols typically either give the size of the frames or provide a specific framing to find beginnings and ends of frames.

**Comment by postHawk** [comment]
Tnx
