### ISSUE TITLE
Question : Distributed Ranch

### ISSUE THREAD

**Issue by malomanini** [ninenines/ranch#154]
Hello,
I am currently working on the erocci project (https://github.com/erocci/erocci) with @jeanparpaillon
and I am trying to deploy cowboy on several nodes using ranch on a single node to distributed the requests.
Do you know if there is any way to use ranch with workers on different nodes, or if it is possible to use the OTP application pool ?
And are there any documentation about it ?
Thank you

**Comment by essen** [comment]
Looks like I completely missed this, sorry.

There's no built-in support for Ranch to do that. However I suppose it would be possible considering Ranch expects a protocol module that simply creates the process, so you can most likely implement one that creates that process on any other node. As far as sockets are concerned, they work in a distributed setting AFAIK so there should be little issues on that end.

**Comment by jeanparpaillon** [comment]
Thanks for the answer.
Let's look how to implement it
