### ISSUE TITLE
Add load balancer option

### ISSUE THREAD

**Issue by jeanparpaillon** [ninenines/ranch#155]
Follow-up #154 
Ranch do not have builtin support for distributed deployment.
One solution could be to allow starting protocol with a custom load balancer module.
Proposed behaviour for load balancer behaviour: look at pool module from OTP.

Maybe only one function amongst `pspawn/3` `pspawn_link/3` and `get_node/0` is needed.

**Comment by essen** [comment]
I don't think this is in the scope of Erlang.mk. As I said earlier, all that should be needed is a different protocol module (which can start the process differently and then resume whatever normal protocol you have), so as far as Ranch is concerned, there's already a way to plug yourself there should you need to. So you could easily have an application on top of Ranch/Cowboy/.. that prepares the pool and then just replace the normal spawn with the one from pool. But I don't think Ranch should do it directly, that's an entirely different concern from an acceptor pool.

**Comment by essen** [comment]
Closing for reasons mentioned in previous commit. I wouldn't be against an example showing how to do it, but I don't think Ranch needs to do anything else to make it work. Please open if you find a specific issue when trying to implement this.

**Comment by jeanparpaillon** [comment]
Got it. Will try to implement it as a protocol, as suggested, and will keep you informed.
Thanks for your answer
