### ISSUE TITLE
Cannot compile .erl files by make

### ISSUE THREAD

**Issue by mururu** [ninenines/ranch#162]
```
$ git clone git@github.com:ninenines/ranch.git
Cloning into 'ranch'...
remote: Counting objects: 1431, done.
remote: Total 1431 (delta 0), reused 0 (delta 0), pack-reused 1431
Receiving objects: 100% (1431/1431), 485.61 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (896/896), done.
Checking connectivity... done.
$ cd ranch
$ make
 DEPEND ranch.d
$ ls ebin/
ranch.app
```

We can compile those files after executing `make clean` or deleting `ebin/ranch.app`.

**Comment by essen** [comment]
It's an issue I fixed in a recent Erlang.mk. I need to update Erlang.mk in Ranch to fix it. Thanks for the heads up.

**Comment by essen** [comment]
I have updated Erlang.mk but on second thought I am not sure if this would fix it when just cloning the repo. Can you try?

**Comment by mururu** [comment]
Thanks for the quick response. But it hasn't been fixed yet on master. The result is the same with the above.

**Comment by essen** [comment]
I no longer see the issue.
