### ISSUE TITLE
ranch_ssl:do_listen fails when the user-defined protocol supports some ciphers only

### ISSUE THREAD

**Issue by gotthardp** [ninenines/ranch#163]
Situation (facts):
 * By default the `ranch_ssl:do_listen` sets the `ciphers` option of `ssl:listen` to a list returned by `ssl:cipher_suites()`. This list contains all supported ciphers.
 * The [ssl:handle_cipher_option](https://github.com/erlang/otp/blob/maint/lib/ssl/src/ssl.erl#L1136) verifies that the user-defined `ciphers` are supported by the target TLS version.

Problem: The `ranch_ssl:do_listen` fails when the user
 * Does **not** set the `ciphers` parameter, i.e. uses the default value as explained above.
 * **Does** explicitly request a specific TLS version, which supports only a subset of all supported TLS suites. For example when the `{protocol, dtls}` option is used.

This is because `ranch_ssl:do_listen` requests `ssl:listen` with an explicit TLS protocol version and with an explicit list of cipher suites that includes ciphers not supported by this protocol. The `ciphers` parameter supplied must not include the ciphers not supported by the `protocol` selected.

I'd suggest to not call the `ranch_ssl:unbroken_cipher_suites()` functions unless necessary and let OTP to define the default set of cipher suites.

**Comment by essen** [comment]
Which Erlang version? Tests don't set ciphers and run fine on all supported versions/platforms, so you'll have to be more specific.

**Comment by essen** [comment]
Closing because no feedback. Thanks!
