### ISSUE TITLE
Hot code upgrade from v1.2.1 -> 1.3.x fails with distillery (Elixir)

### ISSUE THREAD

**Issue by arnodirlam** [ninenines/ranch#168]
I get the following error message when trying to **deploy a hot code upgrade** built with [distillery](https://github.com/bitwalker/distillery) via [edeliver](https://github.com/boldpoker/edeliver) on our server:

### Error

```
-----> Upgrading release to 0.0.1+75-0a9107d
mesg: ttyname failed: Inappropriate ioctl for device
Release 0.0.1+75-0a9107d not found, attempting to unpack releases/0.0.1+75-0a9107d/vira.tar.gz
Unpacked successfully: "0.0.1+75-0a9107d"
Release 0.0.1+75-0a9107d is already unpacked, now installing.
ERROR: release_handler:install_release failed: {code_change_failed,
                                                <7949.18881.0>,ranch_sup,
                                                139509268189817255664052373644620742049,
                                                {'EXIT',
                                                 {badarg,
                                                  [{ets,new,
                                                    [ranch_server,
                                                     [ordered_set,public,
                                                      named_table]],
                                                    []},
                                                   {ranch_sup,init,1,
                                                    [{file,
                                                      "/tmp/edeliver/vira/builds/deps/ranch/src/ranch_sup.erl"},
                                                     {line,26}]},
                                                   {supervisor,code_change,3,
                                                    [{file,"supervisor.erl"},
                                                     {line,660}]},
                                                   {gen_server,
                                                    system_code_change,4,
                                                    [{file,"gen_server.erl"},
                                                     {line,749}]},
                                                   {sys,do_change_code,5,
                                                    [{file,"sys.erl"},
                                                     {line,552}]},
                                                   {sys,do_cmd,6,
                                                    [{file,"sys.erl"},
                                                     {line,446}]},
                                                   {sys,handle_system_msg,8,
                                                    [{file,"sys.erl"},
                                                     {line,353}]},
                                                   {proc_lib,init_p_do_apply,
                                                    3,
                                                    [{file,"proc_lib.erl"},
                                                     {line,247}]}]}}}

A remote command failed on:

  root@...

Output of the command is shown above if the --verbose option
was used and the commands executed on that remote host are
printed below for debugging purposes:

FAILED with exit status 3:

ssh -o ConnectTimeout=3 root@... 
    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /var/www/vira 
    bin/vira upgrade 0.0.1+75-0a9107d 
```

I've tried upgrading from v1.2.1 -> 1.3.0, 1.3.1 and 1.3.2 with the same result.

### Versions
Elixir 1.4.1
distillery 1.1.2
edeliver 1.4.0
phoenix 1.2.1
cowboy 1.0.4

I could not reproduce the error in the [distillery-test](https://github.com/bitwalker/distillery-test) app yet, but can spend some more time on doing so, if it helps.

**Comment by essen** [comment]
Yes it's not supported currently.

**Comment by arnodirlam** [comment]
Okay, thanks for the quick response.

Any plans to support hot code upgrades it in the future?

I have no idea how much effort it would be, so I can't say if it's worth the hassle. But since all phoenix applications depend on ranch, it would be great to have it support hot code upgrades :)

**Comment by essen** [comment]
I definitely want to support them in the future, I even started a test suite for upgrades a while back, it's just not a priority right now. I don't think it would be too much work otherwise, the main issue is that Ranch does things during supervisor init calls that it shouldn't do.

**Comment by fishcakez** [comment]
If ranch code isn't being changed then the hot code upgrades should still work, just don't run a supervisor ugprade on ranch processes. Likely an autogenerated appup is doing something it shouldn't do.

**Comment by arnodirlam** [comment]
@fishcakez are you saying that it is a problem (maybe class of problems) that could be solved by changing how appups are autogenerated?

> Likely an autogenerated appup is doing something it shouldn't do

This statement by @essen seems to point in a different direction - that the solution is within ranch, not the appup autogeneration:

> Ranch does things during supervisor init calls that it shouldn't do

**Comment by fishcakez** [comment]
Ranch has side effects in a code change (init in supervisor case), which
don't work well with advanced code upgrades.

It would be nice if ranch (and so cowboy) were better OTP citizens but I
imagine the effort is better placed elsewhere because so few people would
require such advanced features.

Distillery automatically generates advanced code changes for any module
that looks like it supports them. This means it should not miss when one is
required by existing code but it may generate one when it is not supported
by the code. Also in many cases it will make a suboptimal choice, maybe 50%
of the time, but only be wrong 5℅. However there isn't an obvious way to
improve that.

This means generated appups need to edited by hand in most situations and
this is one of them. Given that 99+% of open source apps don't account for
appups it will always be required I think.

**Comment by fishcakez** [comment]
Too be clear it's very likely you can edit a few lines of the generated
appups so that it works with ranch. It's not required for ranch to be
patched.

**Comment by essen** [comment]
As for upgrades with Ranch, this is something I want to have in Ranch 2.0 so it will come eventually, however my priority is with Cowboy right now.

**Comment by arnodirlam** [comment]
Alright, thanks very much for going into detail!

I'll close this then and wait for Ranch 2.0 to test it :)

**Comment by essen** [comment]
Hope you are patient. :-)

Cheers
