### ISSUE TITLE
Is ranch_sup a must?

### ISSUE THREAD

**Issue by nestor5** [ninenines/ranch#174]
When using ranch in embedded mode, is it a must to add ranch_sup to my supervision tree?  What if only listen specs are added to my supervision tree?  I tried, it works.

If I add ranch_sup and listeners to a dedicated supervisor, can I use one_for_all for this supervisor?  If ranch_sup or one of the listeners fail, ranch_sup and all listeners will be restarted.

Does the order of starting ranch_sup and listeners matter?

**Comment by essen** [comment]
Up to you really. Restarting all listeners because ranch_sup failed might make sense, restarting everything because a listener failed not so much.

**Comment by nestor5** [comment]
https://ninenines.eu/docs/en/ranch/1.3/guide/embedded/ says "First, you need to add ranch_sup to your supervision tree", I tried only adding listeners to my supervision tree but not the ranch_sup, it works.  Why do we have to add ranch_sup to the supervision tree in embedded mode?

When ranch_sup or one of the listeners fail, does the order of restarting all of them matter?

**Comment by essen** [comment]
Hope you got your answer from another source.
