### ISSUE TITLE
Documentation for ranch protocols with gen_server behaviors

### ISSUE THREAD

**Issue by juhlig** [ninenines/ranch#178]
The current documentation for building a ranch protocol with gen_server suggests an approach which is not quite good, in my opinion.

1. It mixes behaviors, `gen_server` and `ranch_protocol`. Even worse, ranch_protocol defines the callback function `start_link/5`, which is also often used as an entry point for a gen_server (or fsm or statem).
2. It requires to start the gen_server in a peculiar way via `proc_lib:spawn_link`, and messing with internals of gen_server like enter_loop, which is supposed to be abstracted away from Developers implementing gen_* behaviors (for good reasons, I'm sure). This also contains the possibility that it may some day change without notice.

I agree that the timeout approach suggested in issue #104 was terrible, but the current approach is not really a good solution, either.

I'm outlining here an approach that I tend to use in this case:
I have a module implementing the ranch_protocol behavior, let's call it example_protocol. As such, it implements only the `start_link/5` function. All this function does is call the `start_link` function of the associated gen_server (let's call it example_server), passing along the arguments. This gen_server does not call `ranch:accept_ack` yet, since doing it in `init/1` would block infinitely; instead, it does a cast to itself (like `gen_server:cast(self(), accept)`). The arguments handed over from example_protocol may either be passed along in the cast, or stored in example_server's state. `init/1` then returns and nothing is blocked. A `handle_cast(accept, State)` function in example_server then contains the `ranch:accept_ack()`. It is the first action example_server will actually do after being started. This part of my approach was exemplified by Fred Hebert in [Learn You Some Erlang in Chapter 23](http://learnyousomeerlang.com/buckets-of-sockets#sockserv-revisited) (a little way down, in the implementation of sockserv_serv). The same approach works as well for gen_fsm and gen_statem. With gen_statem, however, there is another way of doing it without the cast by using state_enter functions and placing `ranch:accept_ack()` in the initial state's enter function.

All in all, this is somewhat like to the timeout approach, but less ugly ;) My solution, however, keeps behavior implementations seperate, and works without messing with gen_* internals, which is the way it is supposed to be, IMO.

Before I write up anything definite, let me know what you think. I'm lazy, so I would hate to see work go to waste ;) On the other hand, if there is something fundamentally wrong with my way of doing things, I'm eager to learn.

**Comment by essen** [comment]
On 1. It doesn't mix behaviors. The term behavior has two meanings in Erlang/OTP. One is the whole shebang, sys+proc_lib+a callback interface. This is what gen_server is. The other meaning is what `-behavior` does which is just a definition for callback interfaces, some compiler checks and type specs. That's what ranch_protocol is. Note that `-behavior` declarations are entirely optional.

On 1 again. The interfaces are compatible. There is nothing in gen_server that forces you to create start_link functions, and as far as protocols go, the only one we care about is the one Ranch will use. The two go very well together.

On 2. No, `gen_server:enter_loop` is not supposed to be abstracted away. It's a documented function that is specifically meant to be used for this purpose when the default interface is not enough. This is one of a few cases where it's perfectly fine to use it.

> It is the first action example_server will actually do after being started.

It isn't because messages could come in between init and your cast. It's the same problem as using a timeout. There's no race conditions when using enter_loop.

Cheers.

**Comment by juhlig** [comment]
Ok, technically you're right on all your points. I probably didn't explain my intention well enough (sorry, english is not my native language ^^;) My intention is more in the realm of aesthetics and intuitivity.

On your first note to 1: I was referring to the -behavior side of behaviors. By specifying a behavior I explicitly declare (last but not least to others reading my code) that "this module does behave like a gen_server/ranch_protocol should do". And yes, I'm aware that it indeed does both when specifying both those behaviors at once.

On your second note to 1: The two interfaces are compatible, that's true.
Aesthetically, however, this is somewhat in line with what multiple inheritance in languages like C++ is (or, better said, the implementation of multiple interfaces): name clashes may happen. So some of the object-oriented languages forbid it, some allow it, but in the latter case the function has to somehow fulfil both roles.
As for intuitivity, I guess most people (who don't work with ranch) expect start_link to be a start function for the _gen_server_ side of things, probably because it's so often used this way. I asked some coworkers about what they think start_link does, they all agreed that it is a gen_server start function. This might be biased, though, since I do it that way, and most of the Erlang code they eventually read is mine ^^;;;

On your note to 2: I rest my case, you're right. I just wasn't aware of it since I've never seen it in use before.

>> It is the first action example_server will actually do after being started.
>
> It isn't because messages could come in between init and your cast. It's the same problem as using a timeout. There's no race conditions when using enter_loop.

Yes, this is also correct. However, that race condition is easily avoided with the proper matching. When passing along the arguments in the handle_cast and putting it in the state after it instead of putting it in the state at the beginning (in init), any handle_* function that actually requires the connection to be established can match on that part of the state "being there", and the handle_cast for accept can even match on "being not there". Depending on whether there is a catch-all clause or not, any messages arriving before a connection is established (eg, handle_cast for accept has been processed) will either be discarded or will crash the gen_server. That's a use case, though. Similarly, this can be handled in a gen_fsm, and even easier in a gen_statem with state_enter.

Kind regards :)

**Comment by essen** [comment]
`start_link` has absolutely nothing to do with `gen_server`. It is a convention to name functions that start processes synchronously and link this way (as opposed to `spawn_link`, though many `start_link` functions just use `spawn_link` under the hood). Many processes which are not `gen_*` or special processes (`proc_lib`) have `start_link` functions to start them. Ranch just follows the convention.

Race conditions are never easily avoided, especially when you purposefully avoid the one solution that does *not* create race conditions. The documentation should provide examples that are 100% correct, not give bad examples that can subtly break if the user is not aware of all the pitfalls.

**Comment by juhlig** [comment]
Yes, that's just what I meant: it's a naming convention. It "clashes" when implementing a gen_server as a ranch_protocol. Since ranch_protocol demands it, though, that convention must be thrown overboard for the gen_server side of things. Still, I guess that's not really bad, um, _behavior_ ;)
Still, is there some point against keeping things seperate the way I outlined (having a module implementing ranch_protocol that just starts a gen_server/fsm/statem (which then uses enter_loop instead of casts ;)), instead of implementing both in one module? I have actually grown quite fond of this approach ;)

You know, I did just have second thoughts about the last paragraph of my last comment. It actually makes the whole thing more complicated, no matter whether it circumvents race conditions or not, and might therefore easily break.

In fact, since the "messing with internals" point has been cleared (thanks, I learned something today :)), I'm actually satisfied. No objections here any more :)

**Comment by essen** [comment]
I do not see a clash. I do not think anyone would need both the `start_link` used by Ranch and another `start_link` if you're going to write a Ranch protocol that happens to be a `gen_server` under the hood. I do not really see what use case this other `start_link` would have.

I believe your approach is actually incorrect because Ranch will not be aware of this second `gen_server` module you have, and therefore calls to `which_children` or attempts to perform release upgrades will not be aware of it and may fail. This is the `modules` part of child specs in supervisors (and the last element of the tuple in `which_children`). Ranch currently has a hardcoded `[Protocol]` value for this.

**Comment by juhlig** [comment]
On the clash point, yes, you're right. This point is at most an academic one then. Accepted :)

My approach, hm, explained this way, I think I start to see how this works and so why what I am doing is wrong... So I learned something else today :)

Thanks for your patience, and I will close this issue :)

**Comment by essen** [comment]
It's not so much that what you do is wrong, it's more that Ranch does not provide the interface for doing this properly. But I think it should, ultimately. Cowboy would benefit from this being done correctly.

**Comment by juhlig** [comment]
I'll read through the code on monday (I'm on my mobile now, not much fun reading code that way). With the insights gained from this conversation, I should be able to understand better how all the parts work together (the "grand scheme of things" :)).
But put simply, what would be required to achieve this is, one the one hand, a way to pass something like `module` via `start_listener` to the connection supervisor, and on the other hand, for this supervisor to actually use it in the appropriate way?

**Comment by juhlig** [comment]
I have been pondering the point that ranch should support modules other than `[Protocol]` in `ranch_conns_sup`. I did also read through the code a few times.
This seems doable and straightforward, at least on the surface. I'm struggling to find a useful solution, though.

These are the possibilities I see:
1. Set the `modules` as a property of the supervisor, specifiable as a protocol option in `ranch:start_listener`, if not specified, default to `[Protocol]`. `supervisor:which_children` would then contain this in it's reply, for all the children. This seems to me the most transparent solution, but all in all a little meaningless. It would allow for the way I was doing things, but nothing much else.
2. Set the `modules` for each child seperately, specifiable in the return value from `ranch_protocol:start_link`, if not specified, default to `[Protocol]`. But, considering that they are started as acceptors at some point in time and then wait for a (arbitrary) connection which will happen later, or never even, I'm in doubt if this would be at all useful. This solution mostly supersedes the other, though, so in doubt I would go for this one.
3. A combination of 1 and 2, in that when no `modules` are specified via `ranch_protocol:start_link`, use what was specified in the protocol options in `ranch:start_listener`. If that is missing, too, default to `[Protocol]`. This seems overkill, though.

Both approaches would also mean changing internals of running `ranch_conns_sup`. Approach 1 would need to change the state record, approach 2 the representation of the childs in the process dictionary from Pid => Type to something like Pid => {Type, Modules}.
Do you wish to support release upgrades to ranch at all? Does anybody need this? And, do erlang.mk/rebar/relx actually _support_ hot code upgrades of dependencies?

**Comment by essen** [comment]
It's something I want to look at and properly do in a long time in the future. I suspect the correct solution would depend on whether this list of modules can evolve as a result of upgrades (and it probably does). We might be better off simply adding a callback to the protocol module in that case as we would then be able to call it during upgrades to update our state. That's at least if we need to keep that state, otherwise we can simply call it when necessary. I agree the default should be the same as today.

As for tools supporting this or what's the exact state of Ranch with regards to this, I think some experimentation would be in order to figure it out. If you would like to experiment with this go for it, even if it only results in feedback it can be immensely valuable (in which case please reopen the ticket so as to not lose it from sight).

**Comment by juhlig** [comment]
I'm not sure I understand, I guess I'm a little out of my depths here ;) What you're suggesting is something like a `code_change` callback in `ranch_protocol`? That _might_ break existing code, though, and _might_ clash with if a `ranch_protocol` is also a `gen_server`.

As for tools, I think I will experiment, but not today ;) Also, I will open another ticket for this then, since this one started off as something completely different.

**Comment by essen** [comment]
No just a function that returns the list of modules that must be upgraded together.

**Comment by juhlig** [comment]
Ah, ok. well, that should be quite easy, yes?

**Comment by essen** [comment]
I'm sure the code that needs to be written is easy. The test suite is another matter.

**Comment by juhlig** [comment]
how true ^^;;;

**Comment by vmsp** [comment]
Hey. Would it be possible to put up an example, in the user guide, on how to use `ranch_protocol` with `gen_statem`?

**Comment by essen** [comment]
Please use a separate issue, and feel free to send a PR if you figure it out.
