### ISSUE TITLE
ranch_tcp is behaving different as compare tcp_gen

### ISSUE THREAD

**Issue by immnas** [ninenines/ranch#183]
I am getting very strange problem in ranch library.
I am trying to create the tcp server for Chinese GPS devices.
When I use ranch library I dont get packets but when I use gen_tcp I get packets.

Below I am giving spinet of my code I am using. ranch one and  gen_tcp

I am using ranch_listener and  ranch_tcp protocol.
_ranch:start_listener(Protocol, 10, ranch_tcp, Options, **my_protocol**, [{protocol, Protocol}, Args])_
In my my_protocol.erl file
I am using 
  __-module(my_protocol).
  -behaviour(ranch_protocol).
  -behaviour(gen_server).

  %% API
-export([start_link/4]).
%%-export([decode_test/0]).

%% gen_server callbacks
-export([init/1,
         handle_call/3,
         handle_cast/2,
         handle_info/2,
         terminate/2,
         code_change/3])._

-define(SOCKET_OPTS2, [binary, {active, false}, {packet, raw}, {reuseaddr, true}]).

-spec(init(Args :: term()) ->
             {ok, State :: #state{}} | {ok, State :: #state{}, timeout() | hibernate} |
             {stop, Reason :: term()} | ignore).
init({Ref, Socket, Transport, Opts}) ->
    ok = ranch:accept_ack(Ref),
    ok = Transport:setopts(Socket, ?SOCKET_OPTS2),
    Protocol = proplists:get_value(protocol, Opts),
    gen_server:enter_loop(?MODULE, [],
                          #state{protocol = Protocol, socket = Socket, transport = Transport}, ?TIMEOUT).

-spec(handle_cast(Request :: term(), State :: #state{}) ->
             {noreply, NewState :: #state{}} |
             {noreply, NewState :: #state{}, timeout() | hibernate} |
             {stop, Reason :: term(), NewState :: #state{}}).
handle_cast(_Request, State) ->
    {noreply, State}.

-spec(handle_info(Info :: timeout() | term(), State :: #state{}) ->
             {noreply, NewState :: #state{}} |
             {noreply, NewState :: #state{}, timeout() | hibernate} |
             {stop, Reason :: term(), NewState :: #state{}}).
handle_info({command, Command}, State) ->
    do_execute_command(State, Command);
handle_info({tcp, _, <<67, 78, 88, 78, 0, 0, 0, 1, 0, 0, 4, 0, 27, 0, 0, 0, 77, 10>>}, State = #state{socket = Socket, transport = Transport}) ->
    Transport:setopts(Socket, ?SOCKET_OPTS2),
    {noreply, State, ?TIMEOUT};
handle_info({tcp, Socket, Data}, State = #state{socket = Socket, transport = Transport}) ->
    Transport:setopts(Socket, ?SOCKET_OPTS2),
  em_logger:info("RAW DATA: ~w DATA: ~w DATA: ~s HRX: ~s", [byte_size(Data), Data, Data,parse_hex(Data) ]),
    do_process_frame(State,Data),
    {stop, normal, State};
handle_info({tcp_closed, _Socket}, State) ->
    {stop, normal, State};
handle_info({tcp_error, _, Reason}, State) ->
    {stop, Reason, State};
handle_info(timeout, State) ->
    {stop, normal, State};
handle_info(_Info, State) ->
    {stop, normal, State}._

Working code ..

_-module(echo).
-export([listen/1]).

-define(TCP_OPTIONS, [binary, {packet, 0}, {active, false}, {reuseaddr, true}]).

% Call echo:listen(Port) to start the service.
listen(Port) ->
    {ok, LSocket} = gen_tcp:listen(Port, ?TCP_OPTIONS),
    accept(LSocket).

% Wait for incoming connections and spawn the echo loop when we get one.
accept(LSocket) ->
    {ok, Socket} = gen_tcp:accept(LSocket),
    spawn(fun() -> loop(Socket) end),
    accept(LSocket).

% Echo back whatever data we receive on Socket.
loop(Socket) ->
    case gen_tcp:recv(Socket, 0) of
        {ok, Data} ->
            io:format("The value is: ~p.", [Data]),
            loop(Socket);
        {error, closed} ->
            ok
    end._

I have to use ranch_listner so I dont have option to use gen_tcp.
In case of ranch i have used other option like {active, once} and {active, true} also.
when I use {packet, line} it give me partial packets and trunked my packet at <<10>> ..
but gen_tcp give packet always correct.

**Comment by essen** [comment]
`ranch_tcp` is just a thin wrapper on top of `gen_tcp`, so you're effectively calling `gen_tcp` in your code. See https://git.ninenines.eu/ranch.git/tree/src/ranch_tcp.erl

Your code examples are not quite equivalent. If the second snippet works, then it'll work just the same when called using `ranch_tcp`.

**Comment by immnas** [comment]
That's way I said strange issue as I am trying this for last three days.
Yes, I am using OTP in case of ranch not exactly same as gen_tcp.
When I set {active, false} I dont get any packets on ranch.
but {active, false} perfectly on gen_tcp.

**Comment by essen** [comment]
You are using `gen_tcp:recv` in the second example, Ranch would work the same if you were using `Ranch:recv`, it ends up calling the same functions. What I would suggest is trying to convert your second example to look more like the first, using active mode, matching against data directly as you seem to do and so on.

Alternatively you can use `dbg` to trace your Ranch process and figure out what's happening. See https://stackoverflow.com/questions/1954894/using-trace-and-dbg-in-erlang for examples.
