### ISSUE TITLE
Ranch - Lager (Case Clause Mismatch Error)

### ISSUE THREAD

**Issue by SunnyRichards** [ninenines/ranch#185]
Hi,

I am using lager (tag 3.6.1), with the version of ranch (1.5.0 ) I noticed that error_lager_lager_h crashes with a case clause of the form:

error_logger_lager_h exited with reason

{'EXIT',{{case_clause,[**Ref,{ack,<0.3770.0>,{error,normal}}**]}, -- Ranch CRASH EVENT (2 params)

[{error_logger_lager_h,log_event,2[{file,"/home/ubuntu/transecur/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,243}]}

I have raised a ticket in lager also, they didn't respond, please look after this

**Comment by essen** [comment]
That's a lager issue. You might have to send a PR there to speed things up.
