### ISSUE TITLE
Add an example showing how to use `ranch_protocol` with `gen_statem`

### ISSUE THREAD

**Issue by vmsp** [ninenines/ranch#186]
There's already an example showing how to use it with `gen_server`. Adding another for `gen_statem` would cover all cases!
See also #178.

Thank you, Ranch and Cowboy are great!

**Comment by juhlig** [comment]
I don't think it is necessary. The example in the user guide is brief to the point where it can be adapted for `gen_statem` with just substituting `gen_server` with `gen_statem`, and putting the initial state name as the 3rd param for `enter_loop` and the state data as the 4th. There is nothing else specific to `gen_server` in the example. A `gen_statem` example would therefore be almost identical to the `gen_server` example.

**Comment by juhlig** [comment]
Or, are you referring to the source examples, `tcp_echo` and `tcp_reverse` in the `examples` dir? That would make sense, I think.

**Comment by vmsp** [comment]
I was referring to both but yeah, a fully working example like `tcp_reverse` would be the most useful.

**Comment by essen** [comment]
I'm voting for replacing the gen_server examples with gen_statem. I don't think gen_server is all that useful for building protocols.

**Comment by juhlig** [comment]
I second that.
