### ISSUE TITLE
src/ranch_ssl.erl:137: ssl:ssl_accept/3: deprecated; use ssl:handshake/3 instead

### ISSUE THREAD

**Issue by getong** [ninenines/ranch#195]
There is a solution for this, but I don't know how to use it with erlang.mk
```
-ifdef(OTP_RELEASE).
-define(ssl_accept(ClientSocket, SSLOptions), ssl:handshake(ClientSocket, SSLOptions)).
-else.
-define(ssl_accept(ClientSocket, SSLOptions), ssl:ssl_accept(ClientSocket, SSLOptions)).
-endif.
```
copy from joedevivo/chatterbox#127

**Comment by essen** [comment]
Please instead review https://github.com/ninenines/ranch/pull/194 which is what we'll move toward while approaching Ranch 2.0. The warning in question can just be disabled.

Note that your solution is incorrect because ssl:handshake's return value is different.

**Comment by getong** [comment]
Yes, these two functions return different results. The solution is wrong.

**Comment by essen** [comment]
I know it doesn't compile by itself under 21 but Ranch is used as a dependency and Erlang.mk disables warning_as_errors for dependencies so this has little impact on users, it compiles for them.

I'm asking about rebar because to prevent future problems I can generate a rebar.config that will disable warning_as_errors for rebar too, and then we can separately ignore that warning.

**Comment by getong** [comment]
How about this:
```
-ifdef(OTP_RELEASE).
ssl_accept(ClientSocket, SSLOptions) ->
    ssl:handshake(ClientSocket, SSLOptions).
-else.
ssl_accept(ClientSocket, SSLOptions) ->
  case ssl:ssl_accept(ClientSocket, SSLOptions) of
     ok ->
          {ok, ClientSocket};
     {error, Reason} ->
          {error, Reason}
  end.
-endif.
```
The function returns the same result now.

**Comment by essen** [comment]
We've added the warning disabling to the PR I mentioned. It'll be merged when I'm less busy with other things.

**Comment by essen** [comment]
Closing, thanks!

I also confirmed that it did NOT produce an error when used with rebar3 as a dependency, only a warning. If it was producing an error with an other tool, please let me know.
