### ISSUE TITLE
When TLS connection cannot be accepted due to malformed keys `ranch:accept_ack/1` enters a receive loop without a timeout

### ISSUE THREAD

**Issue by michaelklishin** [ninenines/ranch#196]
A RabbitMQ user reports a scenario in which [ranch:accept_ack/1](https://github.com/ninenines/ranch/blob/master/src/ranch.erl#L168) is forever stuck in a `receive` loop and prevents RabbitMQ node from shutting down.

We found a way to reproduce:

 * Configure a RabbitMQ 3.6.16 or 3.7.6 node on Erlang 20.3.x (20.3.6, 20.3.8.1 are both affected) to use text files with blank lines for TLS certificates and keys
 * Open a TLS connection using any client (e.g. Bunny with [a script similar to this](https://gist.github.com/michaelklishin/c8e7f458cd891a38eccee4c6bb7ba4c9)) or `openssl s_client`
 * Try to stop the node using `rabbitmqctl stop`
 * Observe that no connection events are present in the logs and the node does not terminate for a long time
 * Observe that one `rabbit_reader` process is waiting in a `ranch:accept_ack/1` call which waits for a message from another Ranch process.

The termination part can be handled by using better supervision tree timeouts in some areas of RabbitMQ (discussed with @essen in a chat channel). However, @dumbbell and I believe that regardless of the shutdown behavior the forever blocked `ranch:accept_ack/1` call should be considered a bug in Ranch. Connections that cannot be accepted since keys are malformed should be rejected immediately or after a reasonable timeout.

[This `receive` loop](https://github.com/ninenines/ranch/blob/master/src/ranch.erl#L168) should probably have a timeout.

**Comment by essen** [comment]
It's by design. Either the process receives the message immediately, or it is killed. Or, of course, something went terribly wrong, but in that case it's a much bigger issue that needs to be investigated thoroughly. I would be interested in the state for the corresponding `ranch_conns_sup` process.

**Comment by michaelklishin** [comment]
We found a way to reproduce:

 * Configure a RabbitMQ node on Erlang 20.3.x (20.3.6, 20.3.8.1 are both affected) to use text files with blank lines for TLS certificates and keys
 * Open a TLS connection using any client (e.g. Bunny with [a script similar to this](https://gist.github.com/michaelklishin/c8e7f458cd891a38eccee4c6bb7ba4c9))
 * Try to stop the node using `rabbitmqctl stop`
 * Observe that no connection events are present in the logs and the node does not terminate for a long time
 * Observe that one `rabbit_reader` process is waiting in a `ranch:accept_ack/1` call which waits for a message from another Ranch process.

The termination part can be handled by using better supervision tree timeouts in some areas of RabbitMQ (discussed with @essen in a chat channel). However, @dumbbell and I believe that regardless of the shutdown behavior the forever blocked `ranch:accept_ack/1` call should be considered a bug in Ranch. Connections that cannot be accepted since keys are malformed should be rejected immediately or after a reasonable timeout.

**Comment by essen** [comment]
I opened a ticket at https://bugs.erlang.org/browse/ERL-664 with a partial solution to the issue. Thanks!
