### ISSUE TITLE
Ranch listener <<Ref>> received unexpected message {ack,<0.27971.0>,{error,normal}}

### ISSUE THREAD

**Issue by immnas** [ninenines/ranch#201]
I am getting very often this message.
How to debug this issue?
I am using ranch:start_listener(Protocol, ?ACCEPTORS, ranch_tcp,_,_,_]) for my GPS devices which send TCP packets to my server.

**Comment by essen** [comment]
Sounds like you're calling `proc_lib:init_ack` on a process that's not started using `proc_lib:start_link`. Either use `proc_lib:start_link` or don't call `init_ack`.
