### ISSUE TITLE
Add built-in PROXY protocol support

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#204]
~~Maybe.~~ Work has started on this.

https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt

There is already an implementation at https://github.com/heroku/ranch_proxy_protocol

I am partial to it, in particular because of issues when matching the socket in socket messages (the proxy protocol socket isn't the actual socket). I think it would work better as a Ranch protocol module that would pass information forward to another protocol once the PROXY connection headers are processed. I can imagine passing the info forward in a variety of ways, from using the ProtoOpts to creating a private ets table for this purpose to (gasp!) using the process dictionary. But maybe just allow the first two.

**Comment by michaelklishin** [comment]
@essen would you consider adopting `ranch_proxy_protocol` as a Nine Nines project supported by its users (such as the RabbitMQ team)? It has recently gone unmaintained :(

**Comment by essen** [comment]
I think if you need more changes in `ranch_proxy_protocol` you should probably just fork for now. This ticket is about adding PROXY support in Ranch directly (and at the same time, a mechanism to do the same in Gun and parsing/building functions in Cowlib to do the same easily for any client).

Its implementation would differ from `ranch_proxy_protocol` but would not suffer with the issue for matching sockets in messages. Then you can update Ranch in RabbitMQ and remove `ranch_proxy_protocol` entirely. If you want to keep the same interface for any reasons it would also be easy, although Ranch won't provide that due to the aforementioned flaw.

As I've mentioned on Tuesday I'll probably start on that in a week or two.

**Comment by essen** [comment]
I can't use any of these module names if I want to avoid breaking this project: https://github.com/heroku/ranch_proxy_protocol/tree/master/src

This is making naming needlessly difficult.

**Comment by essen** [comment]
The de facto main ticket for this is https://github.com/ninenines/cowboy/issues/1270

**Comment by essen** [comment]
Spent the better part of a week on the parser/builder code that can be seen at https://github.com/ninenines/ranch/blob/master/src/ranch_proxy_header.erl

It's now missing a function to receive the header in a single socket read.

**Comment by essen** [comment]
I've just pushed ninenines/ranch@4b9970bcd725972dbd845e07c34a8ef8409ec04c which adds the function `ranch_tcp:recv_proxy_header/2`.

All that remains for Ranch is to use this in real projects (Cowboy, RabbitMQ) and document the new functions.

**Comment by essen** [comment]
I've documented the PROXY code. I will release 1.7.0 soon with that feature. Closing, thanks!
