### ISSUE TITLE
Listener entries in ETS `ranch_server` table not cleaned up on shutdown when using ranch:child_spec/5

### ISSUE THREAD

**Issue by dumbbell** [ninenines/ranch#205]
In RabbitMQ, Ranch listeners are started automatically by the supervision tree here:
https://github.com/rabbitmq/rabbitmq-server/blob/master/src/tcp_listener_sup.erl#L49-L63

Note that in my local copy, I changed the code to use `ranch:child_spec/5` instead of `ranch:child_spec/6`, plus the new map for transport options. This is not committed yet.

With this setup, we never call neither `ranch:start_listener()` nor `ranch:stop_listener()`.

Unfortunately, `ranch_server:cleanup_listener_opts()`, called by `ranch:stop_listener()`, is not executed in our case. The visible regression is that protocol options are written once to the `ranch_server` ETS table, but subsequent changes are not reflected in this table because `ranch_server` uses `ets:insert_new()`.

This can be tested using rabbitmq-stomp and the following testcase:
```
gmake ct-python t=all:connect_options
```

With Ranch 1.6.0, this testcase never returns (and we reach the common_test timeout).

**Comment by essen** [comment]
Introduced in https://github.com/ninenines/ranch/commit/963f53942f1106771e91a018ac9ad46e3bc6a777

@juhlig can you take a look?

**Comment by juhlig** [comment]
@essen is tomorrow ok?

**Comment by essen** [comment]
Of course. lol

**Comment by juhlig** [comment]
Well, you never know :)

I just start remembering why we did that in the first place. Will discuss matters with you in IRC tomorrow then.

**Comment by michaelklishin** [comment]
FWIW this is a blocker for a new RabbitMQ release.

**Comment by essen** [comment]
If you need to get the release out quickly a workaround is to call `ranch_server:cleanup_listener_opts(Ref)` yourself when the supervision tree containing the child specs is stopped. We are planning to do this automatically in `ranch_server` and issue a patch release after the PR is merged.

**Comment by dumbbell** [comment]
As mentionned in #206, the patch resolves the problem for us. Thanks!

**Comment by essen** [comment]
I've just pushed Ranch 1.6.2 that includes the fix for this. Closing, thanks!
