### ISSUE TITLE
Add {tcp_passive, Socket} in Transport:messages()

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#212]
While `ssl` doesn't seem to have it yet, we should add it to Ranch 2.0 to avoid breaking the interface in the future when we can use it in all transports.

**Comment by juhlig** [comment]
I understand this can't be done before Ranch 2.0 for either `ranch_tcp` or `ranch_ssl` without breaking existing implementations, as the `messages` call would forthwith return a 4-tuple instead of a 3-tuple, correct?

<hr />

On that track, I just noticed that the Transports chapter in the user guide is outdated, as it doesn't mention `{active, N}`:
> There are two kinds of active modes: {active, once} and {active, true}.

**Comment by essen** [comment]
Correct and good point, this will need to be updated for 2.0 as well. I don't want to update it before because Ranch doesn't expose this fully in 1.x.

**Comment by juhlig** [comment]
If we found a nice name for an alternative function, we could have it right now. Though, nothing catchy comes to mind, and it doesn't seem too important to brutally implement it ;)

**Comment by juhlig** [comment]
While we're about to change it, we might even change it from a tuple to a map. This would allow for further additions in the future without breaking things again.

**Comment by essen** [comment]
That wouldn't help since when new messages are introduced they should be considered breaking changes as well.

**Comment by juhlig** [comment]
I wouldn't consider specifically `tcp_passive` a breaking change. It appeared as a consequence of the appearance of `{active, N}`, and didn't change the behavior in relation to `{active, once}`.

Anyway, I guess what I'm trying to put in focus is something like this:

Assume for a moment that we _had_ to implement this _right now_, in Ranch 1.x. We will have no choice but to break existing code. Who wants the new feature will upgrade to the Ranch version that supports it and adjust their code to accomodate for it, no problem for them. But if someone else would want to upgrade Ranch for some other reason (some other feature they want, a bugfix, etc), they would be forced to also change their applications code to accomodate for the changed behavior of `messages/0`, even if they don't need it at all.

In contrast, if we had `messages/0` return a map now, like `#{ok=>tcp, ...}` with implementations accordingly using it like `#{ok:=OK, ...}=Transport:messages()` etc, and would then introduce a new message (eg `tcp_passive`) that only appears in conjunction with a new feature (`active, N}`), any existing implementation will just keep working as before without changes. Implementations interested in the new feature will adapt their code, anyway, so no difference to the previous scenario.

**Comment by essen** [comment]
No I got what you're saying, but socket features that introduce new messages should be treated as breaking changes or otherwise very carefully considered (`{active, N}` is standalone and can be ignored, but other messages may not). I don't necessarily disagree about maps.

**Comment by essen** [comment]
Let's add `{active, N}` to ssl: https://github.com/erlang/otp/pull/2072 https://bugs.erlang.org/browse/ERL-811

**Comment by essen** [comment]
`{active, N}` was added to SSL in OTP-21.3 so we should definitely add the message for 2.0.

**Comment by essen** [comment]
Done.
