### ISSUE TITLE
Missing typespecs for getting socket addresses

### ISSUE THREAD

**Issue by JayH5** [ninenines/ranch#213]
It's possible to start a server with Ranch/Cowboy that listens on things that are not an interface IP/port, e.g. Unix domain sockets. The method described in some of the comments in ninenines/cowboy#803--passing `{local, Path}` as a listen address--works as of Ranch 1.7.1.

The Dialyzer typespecs for things like `ranch:get_addr/1`, however, say that they only return the types `{inet:ip_address(), inet:port_number()} | {undefined, undefined}`. When using Ranch to listen on a Unix domain socket, the returned type is `:inet.local_address()` (effectively `{local, binary()}`, where the binary is the path to the socket file). This also leads `ranch:get_port/1` to return the path to the socket file instead of a port number (not that there is one).

Listening on Unix domain sockets doesn't _seem_ to be very officially supported in Ranch even if it does work since there isn't documentation for it and there probably aren't tests either. So I'm not sure if this is "actually a bug", but people do seem to be using this functionality.

In OTP, functions like [`inet:sockname/1`](http://erlang.org/doc/man/inet.html#sockname-1) return the {IP, port} tuple _or_ [another type](http://erlang.org/doc/man/inet.html#type-returned_non_ip_address) that includes this `{local, binary()}` tuple.

**Comment by essen** [comment]
Sure, let's add it to the types. Might need to fix a few things in Cowboy as well.

**Comment by essen** [comment]
#227 for a work in progress.

We also noted that for ssl we will need to patch OTP as the typespecs are not correct there either.

**Comment by essen** [comment]
I've merged the PR. OTP still need to be fixed, and the feature documented. Closing, thanks!
