### ISSUE TITLE
Unknown type - "ssl_cipher:erl_cipher_suite/0"

### ISSUE THREAD

**Issue by g-andrade** [ninenines/ranch#218]
Dialyzer complains about `ssl_cipher:erl_cipher_suite/0` being an unknown type on OTP versions 21.1, 21.2 and 21.3. 

This warning will sometimes spread to applications that import `ranch` as a dependency.

Up until OTP 21.0 [it was defined](https://github.com/erlang/otp/blob/OTP-21.0.9/lib/ssl/src/ssl_cipher.erl#L56-L60) where expected, but from OTP 21.1 onwards the definition was moved into the [ssl_cipher_format](https://github.com/erlang/otp/blob/OTP-21.1/lib/ssl/src/ssl_cipher_format.erl#L40-L44) module.

I would know how to work around this on `rebar` and create a PR (using `platform_define` macros), but I'm a complete ignoramus when it comes to `Erlang.mk`, so I'll limit myself to reporting the issue.

**Comment by essen** [comment]
It's only worth supporting Dialyzer in the most recent version so please submit a PR updating the type.

**Comment by g-andrade** [comment]
PR #220 opened.

(Alas, I was mistaken when it came to OTP 21.3 - this time the definition was moved into the `ssl' module.)

**Comment by essen** [comment]
Merged, thanks!
