### ISSUE TITLE
Cleanup test output

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#234]
When we expect errors there should be nothing printed to the console. See `ct_helper_error_h:ignore/3,4` usage in Cowboy.

**Comment by essen** [comment]
So that's the log that occurs when the gen_server's parent terminates for a non-normal reason. Dunno if it's possible to silence two specific processes. Probably via http://erlang.org/doc/man/logger.html#add_primary_filter-2 or some other filter. The test could add/remove this filter at the beginning and end of the test and the test should be very specific about the pids it filters.

**Comment by essen** [comment]
Note that there's a new PR doing some changes to this particular log so let's make sure we are forward compatible: https://github.com/erlang/otp/pull/2265

**Comment by sirihansen** [comment]
erlang/otp#2265 does not alter the content of this log event, except the `report_cb` fun given in the meta data, so I don't believe it should be any issue with the compatibility here.

**Comment by essen** [comment]
Thanks for the info!

**Comment by essen** [comment]
Merged, thanks!
