### ISSUE TITLE
Increase the default max_connections

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#240]
Probably safe to increase as hardware gets beefier. Sounds like the current default might be too low now.

**Comment by juhlig** [comment]
What value do you propose?

Don't forget that `max_connections` is now per conns_sup, so with the default values there (`num_acceptors=10`, `num_conns_sups=num_acceptors`), the listener-wide default already is 10 times the ranch 1 default.

**Comment by essen** [comment]
Oh right. Well then no need.
