### ISSUE TITLE
Add a draining process

### ISSUE THREAD

**Issue by josevalim** [ninenines/ranch#247]
Ranch has recently added `wait_for_connections` and `suspend_listener` APIs which allows anyone to perform connection draining.

We have been planning to use this API to add automatic draining to Cowboy's Elixir adapter. But before we do that, I thought I would open up an issue here and see if you would like to have built-in draining in Ranch itself.

Recent OTP versions will automatically translate SIGTERM into `init:stop/0`. Since `init:stop/0` shuts down all applications and their supervision trees, in order to perform draining in such cases, all you need to do is to add a process somewhere that traps exits and invokes the relevant Ranch APIs on `terminate/2`. This is much cleaner than setting up custom OS signals.

So the proposal is to start a new process inside ranch supervisor, after `ranch_acceptors_sup` and `ranch_conns_sup`, which is a simple `gen_server` that traps exits and then suspends the listener and drain connections on terminate.

The shutdown time of said process will be customizable, allowing shutdown to continue if draining does not conclude in a reasonable time interval. If desired, this behaviour could be opt-in.

Thoughts?

**Comment by juhlig** [comment]
I'm not the one calling the shots here, but lets say I'm skeptical.

Suspending works by telling the respective listener sup to terminate its acceptors sup, which in turn stops the acceptors and closes the listen socket. By placing the proposed `gen_server` _after_ the others, calling suspend would deadlock, as the listener sup is then waiting for just that `gen_server` to finish shutdown and won't listen when told to terminate the acceptors sup. By wedging it between the acceptors sup and the connections sup, we actually get suspending for free, as the acceptors sup will be shut down first (which equals suspended then), then the gen_server, finally the conns sup. So far, so good.

If I understand you right, the proposed `gen_server` should delay its own shutdown via `wait_for_connections`, thereby delaying the shutdown of the connections sup. Ok.

However, we have to consider that this must also work with more than just one listener. If we drag out the shutdown of one listener, it means that other listeners will begin shutting down only when the listener in question has been drained. In turn, this next listener may also want to be drained, so the shutdown of the ranch application as a whole would be dragged out considerably.

While this may or may not be of relevance to anyone when just the application (and not the entire node) needs to be stopped, there is a catch in the special case of `init:stop`. IIRC, the running applications are stopped sequentially, in reverse order, on `init:stop`, and there is a timeout (30s? Probably configurable...) of how long all that may take before it just exits. By dragging out the shutdown of some applications for too long, you are at risk that other applications started before it won't be shut down properly.

**Comment by essen** [comment]
The biggest problem is probably the application shutdown order. If UserApp depends on Ranch, then UserApp will be shutdown before Ranch. If UserApp is shut down then chances are the connections will not survive for long except for the simplest applications. I don't think we can do this from the Ranch supervision tree.

That said if you have a process that does the job and clear instructions on how to use it, I think it's fine including it in Ranch.

**Comment by juhlig** [comment]
There was a similar feauture request, #175. A little outdated now, as it predates `suspend_listener` and `wait_for_connections`.

I think an approach to do what you want (outside of ranch, because of what @essen just pointed out) is to bake a `prep_stop` into your application that suspends and drains a listener before it stops.

**Comment by josevalim** [comment]
Thanks @juhlig and @essen. Both points are excellent:

1. This won't work for supervisors running inside Ranch itself

2. This is not the most efficient way to do things if you have multiple listeners

So I agree it is best to keep it in our own app. :+1:

**Comment by essen** [comment]
Whichever solution you end up with please come back to us so we can document it.

**Comment by josevalim** [comment]
As asked, here is the solution we shipped with: https://github.com/elixir-plug/plug_cowboy/pull/14. It is a process that trap exits and then shuts down all or the given refs.

**Comment by essen** [comment]
Thanks!
