### ISSUE TITLE
Cowboy's HTTP handler crashes

### ISSUE THREAD

**Issue by saleyn** [ninenines/ranch#253]
It seems that either this code is incorrectly handling the number of arguments (3) in the connection handing lib:
https://github.com/ninenines/ranch/blob/master/src/ranch_conns_sup.erl#L124

or in case of the cowboy lib, it defines the connection initiation function with the wrong number of arguments:
https://github.com/ninenines/cowboy/blob/master/src/cowboy_clear.erl#L22

This leads to a failure to spawn an HTTP connection handler.

**Comment by essen** [comment]
Normal since Ranch master is the upcoming Ranch 2.0. You'll need this Cowboy PR: https://github.com/ninenines/cowboy/pull/1382
