### ISSUE TITLE
Add experimental ranch_socket transport

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#258]
This transport would only be available on OTP-22.0+ (and for Windows, not be available until a future release). It would use the new `socket` API directly: http://erlang.org/doc/man/socket.html

It should be straightforward except for the active mode where it will have to emulate it by creating a separate process that does the recv.

The main goal initially should be to check whether this module brings performance improvements compared to `ranch_tcp`.

**Comment by juhlig** [comment]
Hm, I guess some hammering-into-shape might be required. I have yet only skimmed the `socket` module. Might give it a try later :)

**Comment by essen** [comment]
Mind the priorities, this can wait until after 2.0.

**Comment by thbar** [comment]
I'm just discovering Ranch, so sorry if this is completely out of relation, but in case: do you think this might be what is required to make sure we can work with systemd socket activation (which I hope could reduce downtime at systemd restart time for simple setups)?

I'm trying to achieve that (and apparently a bunch of other people are interested too, such as @tsloughter), but so far I'm getting `einval` errors (for more context, https://elixirforum.com/t/socket-activation-with-systemd-to-reduce-downtime-on-restart/23763).

If that's completely unrelated, sorry!

**Comment by essen** [comment]
This is most likely unrelated.

**Comment by essen** [comment]
The `socket` documentation http://erlang.org/doc/man/socket.html says that timeouts can be set to `nowait` allowing async accept/connect/recv/send calls. If true this is huge and I need to experiment with this quickly.

**Comment by juhlig** [comment]
Hm... apart from the actual implementation of such a transport, only the async accept would affect ranch. connect and recv already accept a timeout parameter, so only the specs would need to be changed. send does not, so we need another function that does (and maybe just ignores it in the other transports). connect and recv are not used inside ranch, so what is passed to them and how it is handled is entirely up to the user. send is used for the sendfile fallback, apart from that it is user-only as well. accept is trickier i guess, it would need adaptions in ranch_acceptor to work or be of any effect. Right?

**Comment by juhlig** [comment]
Btw, the docs say
> Note that all other users are **locked out** until the 'current user' has called the function
What does "locked out" mean here?

**Comment by essen** [comment]
Dunno! But you're incorrect about connect/recv/send, here they will return immediately and you get a message, compared to the blocking functions we have currently. And yes I'm mostly talking about accept anyway, because this changes everything and acceptors would probably need a sync/async accept mode where they behave differently depending on the transport. But this can probably wait until after 2.0.

**Comment by juhlig** [comment]
Hm, you probably got me wrong. As I read it from the docs (eg, for [recv](http://erlang.org/doc/man/socket.html#recv-1), connect/recv/send will work in a blocking way when given a proper `timeout()`. When given `nowait` instead, they will send messages if there is nothing/not enough to read etc, otherwise return the data, etc. connect/recv/send are give or take used by protocol implementations, not ranch itself. So if a user passes `nowait` instead of a timeout, he should also be prepared for messages.

> But this can probably wait until after 2.0.

Didn't you say "quick"? :)

**Comment by essen** [comment]
I don't care about the proper timeout. Even if there wasn't one it could easily be implemented using `nowait`. The important part is async accept.

Experiments can be done before 2.0 even if the feature is only added later.

**Comment by alesasnouski** [comment]
@essen , you may start from https://github.com/alesasnouski/ranch/tree/ranch_socket.
This is a draft and not everything works but it was enough for me to test xmpp server. You can encounter core dump " assert !descP->currentAcceptor.env) - simply remove line `ESOCK_ASSERT(!descP->currentAcceptor.env);` from socket_nif.c (line 6367 as of now) and rebuild your Erlang 22.

**Comment by essen** [comment]
Thanks. About core dumps see if I already reported that one, and if not and it still occurs in 22.2 please open a ticket. I reported a few already but there's probably more.

**Comment by essen** [comment]
Considering the work done to have a socket version of gen_tcp in 23, and the current state of socket (with iolists being converted to binaries and such) let's close the ticket for now and go back to the subject later on.
