### ISSUE TITLE
Add support for {handshake,hello} for ssl

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#270]
In ssl it's possible and sometimes necessary to perform some operations during the handshake. We therefore should provide direct support for `{handshake,hello}` by having `ranch:handshake` return extra information in a map (not necessarily matching ssl's return value) and add a `ranch:handshake_continue/1,2` that would resume the handshake.

Related:

* https://github.com/rabbitmq/rabbitmq-server/issues/2060
* https://bugs.erlang.org/browse/ERL-1016

**Comment by juhlig** [comment]
Seems straightforward enough. I'll check it out on tuesday.

**Comment by essen** [comment]
Done, thanks!
