### ISSUE TITLE
Under-the-hood documentation for Ranch

### ISSUE THREAD

**Issue by NicoGim** [ninenines/ranch#277]
Hi!

I have been working in August on analysing the Ranch source code.
Originally, it was just for me to learn more about Erlang and get inspired by a solid library for my own projects.
But at the end, it came up being quite a long walkthrough as I was putting more and more efforts in the note I was taking alongside.
Finally, I ended up writing documentation that links with the source code, and creating new schemas explaining the concepts and how things work together.

I haven't published the documentation in a readable format quite yet. But you can already pull this GitHub repo and use Asciidoctor to generate a nice HTML.

Here is the link:
https://github.com/baozi-technology/ranch-hunder-the-hood

I am currently working on my website, I'll publish the documentation there.
It would be an honour for me if you decide that it is worth publishing on the Nine Nines website as well.
  
But for now, it is just the first version and I was pretty new to Erlang when writing it. So I may have made mistakes. Feedbacks are highly appreciated!

EDIT: documentation is avalaible at https://baozi.technology/ranch-under-the-hood

**Comment by juhlig** [comment]
@NicoGim @essen Thanks, will read :)

**Comment by essen** [comment]
I would welcome linking to a published version of this from the README and the `Internals` chapter of the documentation. I could also add this as-is directly to ninenines.eu if you want (perhaps as a mirror of your own version).

I am thinking of releasing an rc2 this week and then do an rc3 once release upgrades are working properly (just a matter of testing right now). So there's still time before 2.0.

**Comment by NicoGim** [comment]
Hi @essen!

I still haven't had time to review the feedbacks from @juhlig and update the doc.
Was working on my personal website aside from work. Was planning on releasing the guide there as well. 

I'm happy with any use you want to make with this documentation - really :).

I think the easiest way for you would be to embed it as is directly to ninenines.eu.
Perhaps in a new section where you could release the `Internals` chapter too.
A go-to place for developers or advanced users who want to know more about Ranch. Maybe potential new Contributors or just because they don't understand some unusual behaviour they observe using the tool.

I didn't know about the `Internals` chapter before I cloned the project and studied it for some time. I assumed the `guide` directory was the same content as the one published on ninenines.eu.

I think if I had read it before studying the source code it would have helped me a lot.
For example, I couldn't get the difference between a connection process and a Protocol handler when going through the documentation. It was educational for me to get information about the Ranch architecture directly looking at the code but it would definitely have been faster looking at `Internals` first.

That's why I think it would benefit the whole community to have it all in ninenines.eu.

Another way would be for you to simply link to my website where a readable version of the guide will be published. I'm fine with anything, really.

I'll be happy to update the guide once 2.0 will be ready to be released.

Cheers,
Nico

**Comment by NicoGim** [comment]
Hi there,

I finally published the documentation:
https://baozi.technology/ranch-under-the-hood

Warning: the site is still under construction. It is not responsive yet, especially not compatible with small screens and mobiles. I want to put the table of contents on the side as well.

Cheers,
Nicolas

**Comment by essen** [comment]
I'm waiting for CI to finish before I push but this is what I'll be adding to the user guide, internals section, at the end of its intro:

``` patch
diff --git a/doc/src/guide/internals.asciidoc b/doc/src/guide/internals.asciidoc
index c5bde58..600920f 100644
--- a/doc/src/guide/internals.asciidoc
+++ b/doc/src/guide/internals.asciidoc
@@ -10,6 +10,11 @@ matter to you. Generic benchmarks found on the web may or may not
 be of use to you, you can never know until you benchmark your own
 system.
 
+A third party dive into the internals of Ranch is available should
+you be interested: https://baozi.technology/ranch-under-the-hood/[Ranch: what's under the hood?]
+We make no claims with regard to its freshness or accuracy but this
+is a nice document to read along this section.
+
 === Architecture
 
 Ranch is an OTP application.
```

Thanks!

**Comment by NicoGim** [comment]
Thanks to you.

**Comment by nicobao** [comment]
For info, I just changed the license of my "Ranch walkthrough documentation" to the same license as Ranch, ISC License. Feel free to pick the things you find interesting to add in the already existing documentation, if you want.

**Comment by essen** [comment]
Thanks for the heads up! Cheers.
