### ISSUE TITLE
ranch_protocol:start_link no longer receives the socket?

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/ranch#282]
We have some code in our protocol that logs the peer before continuing the SSL handshake -- this is important for diagnosing, well, SSL handshake failures: if we log the peer before it fails, we can get a tcpdump running against it ready for the next time.

In ranch 2.x, `Protocol:start_link/3` no longer receives the socket, which means that this is no longer possible.

It _looks_ like we could just do the same in `Transport:handshake`, before calling `ranch_ssl:handshake`. Is this the recommended place to do this?

**Comment by essen** [comment]
The recommended documented place yes. It's the earliest time you will get the socket.

An alternative is receiving the message and sending it back to yourself after you're done, but that should only be used when everything else fails.
