### ISSUE TITLE
listening specific IP

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/ranch#286]
i hate to ask, but i am failing to find in the docs (both Ranch and Cowboy)
how to bind a listener to a specific interface?
i have hidden my Cowboy behind an nginx, now i really want it stop listening 0.0.0.0

**Comment by essen** [comment]
https://ninenines.eu/docs/en/ranch/2.0/manual/ranch_tcp/ `ip`

**Comment by eugene-panferov** [comment]
thank you.
if you are up to improve the docs about it, note:
i failed to even look into this particular page "ranch_tcp" -- had no idea no link
i googled the type name ranch_listener:opts() -- no results

**Comment by essen** [comment]
Well the type is `ranch:opts()` and the first result is the `ranch` manual page which tells you to check the transport module you are using.

**Comment by juhlig** [comment]
I guess this issue can be closed, no?
