### ISSUE TITLE
ranch_server probably needs update instead of load_module

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#290]
In .appup. We want to call `code_change` on all gen modules. Review and fix if necessary.

**Comment by juhlig** [comment]
In that case, `ranch_server_proxy` needs update instead of load_module, too, as it is a `gen_server`, yes?

**Comment by essen** [comment]
Probably. Try putting `io:format` in `code_change` and see if they're called with `load_module` first to confirm. But I think the change is necessary.

**Comment by juhlig** [comment]
#291

**Comment by essen** [comment]
Github is stupid and wants me to comment to close the ticket.

**Comment by essen** [comment]
CLOSE WHEN GITHUB STARTS WORKING AGAIN
