### ISSUE TITLE
Want just-in-time TLS & hot cert reloading. Possible & reasonable?

### ISSUE THREAD

**Issue by gerhard** [ninenines/ranch#293]
In certain environments, like K8S, we need to configure SSL before the certificate was generated. We also need to be update the SSL certificate in use without taking down the entire app. Updating the cert in place so that all new connections will use it should be enough. It may be worth forcing existing connections to close, but I think this is less important.

Is the above: 1. Possible and 2. Reasonable ?

cc @michaelklishin @mkuratczyk @dumbbell @Zerpet @Jrmcneil

**Comment by essen** [comment]
If you use `certfile` the certificate will be updated when it changes on the disk. Connections will be refused in the meantime if there is no cert.

**Comment by juhlig** [comment]
Not 100% sure, but [`ssl:clear_pem_cache/0`](http://erlang.org/doc/man/ssl.html#clear_pem_cache-0) may be worth looking into for your use case, too.

**Comment by essen** [comment]
Also see `ranch:suspend_listener/1`.
