### ISSUE TITLE
Predicates to find out if a listener is suspended

### ISSUE THREAD

**Issue by michaelklishin** [ninenines/ranch#295]
@essen there is currently no predicate functions in the API that would allow for checking if a listener is currently suspended. It is possible to do this by inspecting listener supervisor children or use `ranch:info/1` but it would be great to have a couple of predicates that accept a Ranch listener ref.

Would you accept such change if I contribute it or is `ranch:info/1` sufficient in your opinion?

**Comment by essen** [comment]
There's `ranch:get_status/1`: https://ninenines.eu/docs/en/ranch/2.0/manual/ranch.get_status/

**Comment by michaelklishin** [comment]
Oh, thanks, I somehow have missed this.
