### ISSUE TITLE
Move ebin/ranch.app to src/ranch.app.src

### ISSUE THREAD

**Issue by sigsergv** [ninenines/ranch#304]
It would be much cleaner to move file ranch.app from the directory ebin. It often considered as artifacts directory and removed during cleanup process for example.

**Comment by essen** [comment]
It can be removed it's fine it'll just be rebuilt on the next build. If using Rebar it's necessary for compatibility. Not sure what you're using that would delete it.

**Comment by sigsergv** [comment]
The problem is when it's removed rebar doesn't recognize ranch directory as a valid distribution.

**Comment by essen** [comment]
Yes but Rebar doesn't remove it so I'm not sure what the problem is?

**Comment by sigsergv** [comment]
We are deploying code to build server ignoring all ‘ebin’ (along with some others) directories.

**Comment by essen** [comment]
So just ignore `ebin/*.beam`.
