### ISSUE TITLE
How to set max_connections globally?

### ISSUE THREAD

**Issue by vdimir** [ninenines/ranch#306]
One option is to set `num_acceptors` to one, but not sure that it is a good idea.

**Comment by essen** [comment]
Not sure what you're asking exactly?

**Comment by vdimir** [comment]
> Not sure what you're asking exactly?

I wonder how to set hard limit for number of simultaneous connections for my server? E.g. if I set 100, only 100 clients can be accepted. Other ones would wait and not be served, or be rejected.

**Comment by essen** [comment]
You could always write a transport to enforce this, but your accept rate will suffer. Or you could have a single acceptor as you mentioned, with the same accept rate issue. Otherwise this is a soft limit.

**Comment by vdimir** [comment]
Got it, thanks!

**Comment by JeppeTh** [comment]
I don't understand this max_connections - from my testing it seems sockets still are accepted - i.e. no possibility to protect yourself?
Only HTTP layer is blocked?

**Comment by essen** [comment]
Note that in Ranch 2.0 the `max_connections` is per conns_sup, so the real max is `max_connections * num_conns_sup`. Otherwise the sockets might sit on the backlog before they get accepted.

**Comment by JeppeTh** [comment]
Uncertain which version we're running but can't find this num_conns_sup - so I guess not 2.0. 
We set num_acceptors to 1 and got a difference in behaviour though - but I will check with wireshark - ur just use telnet etc to check if it's just Gun that hides that socket was closed for me.

**Comment by essen** [comment]
Like I've said the limit is a soft limit, so unless all acceptors get blocked then some connections can keep being accepted, and acceptors only get blocked after they accept a new connection and the total is higher than allowed. So you may get up to `max_connections + num_acceptors`.

**Comment by JeppeTh** [comment]
I have one acceptor - max connections set to 3 and still manage 6 sockets (can't try more in my test environment - have limited ports).
Is acceptor supposed to get blocked when max_connections are achieved you mean?

**Comment by essen** [comment]
Acceptors don't all get blocked at the same time, accepting new connections is a synchronous call so acceptors cannot get blocked while they are trying to accept a connection, only after.

**Comment by JeppeTh** [comment]
Ok,  i understand but I should only have one acceptor. Perhaps something wrong in my version...

**Comment by essen** [comment]
I'm available for consulting if needed. Hard to say without the code. The feature is tested at https://github.com/ninenines/ranch/blob/master/test/acceptor_SUITE.erl#L1012-L1074

**Comment by JeppeTh** [comment]
I now realize the problem - not calling gen_tcp/ssl:accept doesn't prohibit new sockets from being accepted. I.e. OTP/Linux accepts them anyhow. I guess these accept messages ends up in the message queue in ranch waiting to be read by calling accept.
