### ISSUE TITLE
How can gen_tcp be configured to support both IPv4 and IPv6 connections

### ISSUE THREAD

**Issue by SisMaker** [ninenines/ranch#310]
If gen_tcp:listen listens to a port, then it can connect to a client that supports IPv4 and IPv6 addresses. How can I do this?

**Comment by essen** [comment]
Ranch provides only a thin wrapper on top of gen_tcp so the same considerations apply.

**Comment by dch** [comment]
@SisMaker you may find https://github.com/hrefhref/erlang-dualstack helpful, it might be possible to integrate this into ranch with some effort. I've not looked at the code, of course. It depends on how much different in behaviour there is.

**Comment by SisMaker** [comment]
> Ranch provides only a thin wrapper on top of gen_tcp so the same considerations apply.

thank you very much！

**Comment by SisMaker** [comment]
> @SisMaker you may find https://github.com/hrefhref/erlang-dualstack helpful, it might be possible to integrate this into ranch with some effort. I've not looked at the code, of course. It depends on how much different in behaviour there is.



> @SisMaker you may find https://github.com/hrefhref/erlang-dualstack helpful, it might be possible to integrate this into ranch with some effort. I've not looked at the code, of course. It depends on how much different in behaviour there is.

It seems to give me the answer. I'll take a closer look， thank you very much！
