### ISSUE TITLE
Release Ranch 1.8 that is compatible with OTP-24

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#314]
This will give me time instead of having to release a Cowboy 3.0.

**Comment by essen** [comment]
RabbitMQ needs this. /cc @lhoguin

**Comment by michaelklishin** [comment]
We decided to go with 2.0 at least for RabbitMQ 3.9 https://github.com/rabbitmq/rabbitmq-server/pull/2878. This may make sense for 3.8, though.

**Comment by Taure** [comment]
===> Compiling ranch
_build/default/lib/ranch/src/ranch_ssl.erl:142:7: Warning: ssl:ssl_accept/3 is removed; use ssl_handshake/1,2,3 instead

When I compile Cowboy with otp24 rc1 is it any plan to solve this? Not sure if this is the correct ticket to discuss this.

**Comment by essen** [comment]
This is the correct ticket, but I am probably not going to do this before May.

**Comment by Taure** [comment]
Is it something else that need to be fixed than ssl:ssl_accept?

If it is only this I maybe can have some time to look at it.

**Comment by essen** [comment]
What takes time is producing the releases.

**Comment by essen** [comment]
https://github.com/ninenines/ranch/tree/1.8.x

**Comment by essen** [comment]
The build looks good enough. It would be good to have folks test the 1.8.x branch and report any compiler or Dialyzer warnings. I plan to produce the release soon after OTP-24.0-rc3. Thanks!

**Comment by essen** [comment]
The branch is ready. Barring any unforeseen issues, I will release 1.8.0 tomorrow. CI will not be green but the errors are either caused by OTP, by a Concuerror problem with OTP 24 or are the usual Windows errors.

**Comment by essen** [comment]
On second thought let me make sure there are no problems on the Cowboy/Cowlib/Ranch combination before I release one. We'll know later today.

**Comment by essen** [comment]
All good. I have tagged Ranch and Cowlib. I still need to tag Cowboy and finish up the release. Not today though.

**Comment by essen** [comment]
2.0 is already compatible with OTP 24. The only issue is that 1.x isn't, and 1.x is used by Cowboy by default.

**Comment by comptekki** [comment]
OK.  Thanks.  I had noticed that Cowboy was using 1.x and wondered about 2.x.  That makes more sense now!

**Comment by essen** [comment]
Done.
