### ISSUE TITLE
Add a function that converts from ProxyInfo to ssl:connection_information/1 return value

### ISSUE THREAD

**Issue by lhoguin** [ninenines/ranch#318]
For easier interoperability between PROXY ssl and normal ssl.

See https://github.com/rabbitmq/rabbitmq-server/pull/3175/files for what could be the start of an implementation.

**Comment by essen** [comment]
Would be good for 2.1.0 but not a deal breaker.

**Comment by essen** [comment]
This is done and just needs to be pushed.
