### ISSUE TITLE
Update appup for 2.1.0

### ISSUE THREAD

**Issue by essen** [ninenines/ranch#326]
cc @juhlig 

What should we apply? Same as before?

**Comment by essen** [comment]
I think we just need to copy paste the existing appup contents changing the first version from `2.0.0` to `2.1.0`. I think that's what we concluded last time. Correct, @juhlig ?

**Comment by juhlig** [comment]
I _think_ we did, FWIW... Not 100% sure TBH, it's been a very long time.

**Comment by essen** [comment]
OK. Yes I think as long as we don't add or remove any new modules (or change them as behavior) it should work the same across versions. Done. Thanks!
