### ISSUE TITLE
The user guide links on the README are broken

### ISSUE THREAD

**Issue by dewetblomerus** [ninenines/ranch#328]
It looks like the readme for this version of Ranch is broken.

If a new person comes to the README on `master` they experience broken links because there is not yet a guide.

As of this writing, the links go to `2.1` but there is not `2.1` here https://github.com/ninenines/ninenines.github.io/tree/master/docs/en/ranch

I figured out that if I select the `2.0` tag I can get to the documentation.

Could we either have the link point to the last working version of the documentation `2.0` today, or add a `not yet released` page to the docs website here https://ninenines.eu/docs/en/ranch/2.1/guide

**Comment by essen** [comment]
We are preparing a release it'll work when that release is out.
