### ISSUE TITLE
ranch:handshake(Ref) silently drops invalid TLS connections in ranch_ssl via exit(normal)

### ISSUE THREAD

**Issue by p-kraszewski** [ninenines/ranch#336]
I am building a system with mutual certificate verification.
I'm using OTP-ized mode with ranch 2.0.0

```erlang
start_link(Ref, Transport, ProtoOpts) ->
    lager:debug("START_LINK ~p/~p/~p~n", [Ref, Transport, ProtoOpts]),
    {ok,
        proc_lib:spawn_link(?MODULE, init, [
            #{ref => Ref, transport => Transport, opts => ProtoOpts}
        ])}.

init(Arg) ->
    lager:info("INIT ~p~n", [Arg]),
    #{ref := Ref, transport := Tr} = Arg,
    case ranch:handshake(Ref) of
        {ok, Socket} ->
            lager:info("INIT handshake ~p~n", [Socket]),
            Tr:setopts(Socket, [{active, true}]),
            process_flag(trap_exit, true),
            gen_server:enter_loop(?MODULE, [], Arg#{sock => Socket});
        E ->
            lager:info("INIT failed ~p~n", [E])
    end.

% ...
```
It works beautifully for valid connections. It fails miserably for invalid connections. In the case of invalid connection (for example a failed TLS handshake), `ranch:handshake(Ref) ` does not return error, but does `exit(normal)` instead, which bypasses the rest of the function.

In particular, the function doesn't know _that_ the connection failed, not to mention _why_.

I partially circumvented the problem with **ugly** use of `catch`:

```erlang
init(Arg) ->
    lager:info("INIT ~p~n", [Arg]),
    #{ref := Ref, transport := Tr} = Arg,
    case catch ranch:handshake(Ref) of
        {ok, Socket} ->
            lager:info("INIT handshake ~p~n", [Socket]),
            Tr:setopts(Socket, [{active, true}]),
            process_flag(trap_exit, true),
            gen_server:enter_loop(?MODULE, [], Arg#{sock => Socket});
        {'EXIT', Reason} ->
            lager:error("INIT crashed ~p~n", [Reason]);
        E ->
            lager:info("INIT failed ~p~n", [E])
    end.
```
I know _that_ connection failed, but still have no idea _why_  (invalid cert, invalid protocol, other reason).

Is there a way to dig-out the exact cause of the error (and the IP of the failing party), or should I just switch to `ranch_tcp` and perform ssl/tls negotiation manually, in handler?

**Comment by essen** [comment]
We could probably `exit({shutdown, Reason})` instead.

**Comment by p-kraszewski** [comment]
And how about not using `exit()` at all, as God intended us to use Erlang?

"And Joe said: _thou shalt not use catch/exit/try/throw for program flow control_".

**Comment by Maria-12648430** [comment]
> "And Joe said: _thou shalt not use catch/exit/try/throw for program flow control_".

The important point being in the "_for program flow control_" part, IMO ;) In my understanding, to `exit` is like saying "something is _seriously_ wrong". And since we are talking about a process that handles a connection here, what's more wrong than the connection failing? So, in a nutshell, to exit is the only correct thing to do here (the exit reason being `normal` OTOH, that's most likely _not_ correct ;)).

**Comment by p-kraszewski** [comment]
Well, in my daily job, a failed TLS connection is nothing wrong from _programmers's_ point of view. In particular, it is nothing exceptional enough to pull the `exit()` gun. Just another attempt to break-in, DoS or ports can. You don't eject your pilot seat just because a bird pooed on your windshield...
On the other hand, it is **very** interesting from _administrator's_ point of view (_why_ it failed, _who_ tried to connect). Interesting enough to log _all_ the relevant details in application/system log. The keyword here: _all_.

I patched `ranch.erl` to return `{error, Reason}` rather than `exit(normal)` (or even the proposed `exit({error, Reason})`) in case of failed TLS (as a temporary patch - I have no idea if it wreaks havoc deeper in the library, or in, say, `cowboy`, which will also be used in the project). I could now cleanly get _reason_, but still had no idea how to dig out the _originator_ -- there's no place to sensibly call `getpeer/2`: on a failed `hanshake/1` both TLS and TCP sockets are (quite correctly) closed before a call to `exit(normal)` (or return) and before `hanshake/1` I don't have `socket()`.

I reversed my code back to `ranch_tcp`, catch originator's IP after successful `hanshake/1` (which fails only after a serious FUBAR from the system anyway) and then perform a manual upgrade to TLS. Plenty of data to (eventually) log, clean error flow.

If you'd want some assistance with the issue, I'd gladly help in my free time, but I'd need some insight on `ranch` control flow.

**Comment by essen** [comment]
I think if you need fine grained info then `ranch_tcp` is the way to go. We have pondered whether to make `ranch_ssl` use `gen_tcp` before upgrading for various reasons, and this sounds like one more to add to the list, so if there's any improvement to be done in this area that's most likely what we'll end up doing.

All things to be considered when the time comes to do a Ranch 3.0 in any case.

**Comment by p-kraszewski** [comment]
I'm open to cooperation. I suppose this issue might be closed for now. Best regards!

**Comment by essen** [comment]
This issue has come up in RabbitMQ when debugging embedded device issues (they're too slow for default TLS handshake timeouts). It will need to be addressed in Ranch 3.0.

**Comment by Maria-12648430** [comment]
> This issue has come up in RabbitMQ when debugging embedded device issues (they're too slow for default TLS handshake timeouts). It will need to be addressed in Ranch 3.0.

Ok, how do you think should we address it?

A rather easy solution (that could IMO be implemented even now in Ranch 2) would be to return an error tuple instead of exiting, as @p-kraszewski suggested.

Like, here: https://github.com/ninenines/ranch/blob/a8f31f3f0274f7e5a6b58fa6b6090c3160c4d023/src/ranch.erl#L320-L328
The error tuple could be enriched with info obtained via `Transport:peername`, to be called before we (that is, ranch) close the socket. For SSL connections, it might be nice to also have the `peercert`, but that is currently not a `ranch_transport` callback. The error tuple could look something like this `{error, HandshakeError, PeerInfo}`.

There would be a change in semantics, but it would be IMO small:
* Now, a user will likely either do `{ok, Sock}=ranch_handshake(Ref)` or a variation thereof involving `case`, `catch` or `try...catch`.
* After switching to error tuples instead of `exit`s, some of those may result in badmatch or clause errors.

The important point is that, if it didn't work in the current implementation, it also won't work after the change; I wouldn't consider it a breaking change. This is why I say it could already be implemented in Ranch 2.
There are some exceptions, though: In case of a failed handshake, something like...
* `case ranch:handshake(Ref) of {ok, Sock} -> Sock; _ -> whatever end` will exit in the current but return `whatever` in the new implementation
* `try ranch:handshake(Ref) of {ok, Sock} -> Sock; _ -> whatever catch exit:normal -> something_bad_happened end` will return `something_bad_happened` in the current but `whatever` in the new implementation

**Comment by essen** [comment]
I don't think most code cares about connections that don't manage to pass the handshake. Outside controlled environments these failures happen a lot. It could be a TCP client sending garbage, or a client connecting and not sending anything / going through a tunnel, or many other scenarios.

I also don't think there's much value to handling the error tuple beyond logging something for debugging purposes so I wouldn't expect users to handle it.

In that case it makes more sense to just `exit({shutdown, Reason})` like I mentioned before. The process won't exit normally which makes debugging easier, and if really necessary it can be catched and logged.

**Comment by Maria-12648430** [comment]
> In that case it makes more sense to just `exit({shutdown, Reason})` like I mentioned before.

Ok, makes sense. However, @p-kraszewski also complained about not getting any info about the peer, which would still be missing from the exit reason?

**Comment by essen** [comment]
If I'm reading the code correctly it should be possible to call `ssl:peername` before closing the socket as that doesn't go through the ssl connection process.

**Comment by Maria-12648430** [comment]
I mean not obtainable for the user. We can obtain that info in `handshake` before `Transport:close`ing the socket, but we have to include it in the exit reason for the user.

**Comment by Maria-12648430** [comment]
... like this: #345?

**Comment by essen** [comment]
Yes I mean we can call the function before closing.

No not like this it has to be a 2-tuple I think, to be considered a "normal" exit reason by supervisors, so you'll need to wrap the info in another tuple. Otherwise yes. Also, tests!

**Comment by Maria-12648430** [comment]
> it has to be a 2-tuple I think, to be considered a "normal" exit reason by supervisors

Well, the supervisor in question would be `ranch_conns_sup`, which is not a run-off-the-mill supervisor, so it could be made to accept this. But yeah, no need to make things complicated, I wrapped it in an extra tuple as you said in the last commit.

> Also, tests!

I'll have to come back to that later, they're more work than the actual change, and I'm ~supposed to be~ busy with other things :innocent: I'll ask @juhlig (\*poke\*) if he can take them on, not sure how busy he currently is :woman_shrugging:

**Comment by juhlig** [comment]
> I'll ask @juhlig (*poke*) if he can take them on, not sure how busy he currently is 🤷‍♀️

~Don't drag me into this~ Happy as I would be to jump in, it turns out that I'm ~supposed to be~ _very_ busy ATM, project deadline looming and all XD I'll see what I can do, but no promises ok =^^=

**Comment by JeppeTh** [comment]
Another variant is to make a wrapper of e.g. ranch_ssl where you can pass on the handshake failures info to the process where you need it.

**Comment by essen** [comment]
Now a shutdown tuple containing the error reason and peer info will be provided. Closing, thanks!
