### ISSUE TITLE
Questions about "gen_tcp:accept/2" and "num_acceptors"

### ISSUE THREAD

**Issue by zhu121** [ninenines/ranch#339]
Version: 2.1.0
The issue is：
How to determine the value of "num_acceptors" in the scenario of handling large concurrent connection requests, and whether "gen_tcp:accept/2" is replaced by "prim_inet:async_accept()" would be more appropriate

**Comment by essen** [comment]
Benchmark!

Using an undocumented function that will almost certainly be removed once `socket` becomes prevalent is not appropriate.

**Comment by zhu121** [comment]
> Benchmark!
> 
> Using an undocumented function that will almost certainly be removed once `socket` becomes prevalent is not appropriate.

Excuse me.
Multiple gen_server processes are monitoring accept, whether to consider the shocking group problem, I can't find relevant information.
