### ISSUE TITLE
ranch:stop_listener/1 throws error

### ISSUE THREAD

**Issue by memer-boy** [ninenines/ranch#340]
Hi, loving Cowboy in my projects. Just found this after bumping from 2.0.0-rc3 to 2.1.0

When you call  ranch:stop_listener with a name of a listener that has never been started, it throws an error; used to do nothing in 2.0.0-rc3 if listener didn't exist at all, or at least returned {error, not_found} like the docs states.

Thank you all for your great work.

**Comment by juhlig** [comment]
Ah, I see the problem :) Will look into it.

**Comment by essen** [comment]
Fixed, thanks!
