### ISSUE TITLE
{error, no_cert} with `certs_keys` from OTP 25

### ISSUE THREAD

**Issue by leoliu** [ninenines/ranch#342]
Ranch returns `{error, no_cert}` when using the new ssl option `certs_keys` from OTP 25 https://github.com/IngelaAndin/otp/commit/34a74ef92d217a6f3600f5a02172fd42a268bf03

**Comment by essen** [comment]
Hmm I don't think we do explicit checks, we just pass to ssl. Can you provide an example of Ranch use where you get this error?

**Comment by Maria-12648430** [comment]
> Hmm I don't think we do explicit checks, we just pass to ssl. Can you provide an example of Ranch use where you get this error?

We do, here: https://github.com/ninenines/ranch/blob/master/src/ranch_ssl.erl#L115-L128

**Comment by essen** [comment]
Yep you're both right. I can look on Monday but a PR is welcome in the meantime.

**Comment by essen** [comment]
@leoliu Hello! Can you try the linked PR and confirm it fixes your issue? Thanks!

**Comment by leoliu** [comment]
@essen Yes `{error, no_cert}` is gone.

**Comment by essen** [comment]
Fixed, thanks!
