### ISSUE TITLE
Add the ability to stop listening, without killing existing connections

### ISSUE THREAD

**Issue by rlipscombe** [ninenines/ranch#83]
Using ranch, is there any way to stop the listener (and acceptors)
without dropping the existing connections?

I ask because I'd like to start another instance of my server on the
same box and have the old instance continue to handle its existing
connections for a while.

It looks to me that if I call ranch:stop_listener, it'll kill the
ranch_listener_sup, which will also kill the ranch_conns_sup (and the
existing connections).

If I manually do a supervisor:terminate_child(ListenerPid,
ranch_acceptors_sup), the acceptors go away, but the socket is still
open, which means that I can't start another instance of my server.

**Comment by rlipscombe** [comment]
So, it turns out that we couldn't do this in our code, because we were using the `socket` option (#123) and we'd also spliced ranch into our supervision tree. This meant that the listening socket was owned by the wrong process.

By changing it to use a custom transport, the listening socket is now correctly owned by the `ranch_acceptors_sup` process.

> There is no specific interface to do it at this point though you can using the supervisor module and whatnot.

```
% Listener ref from cowboy 'echo_get' example.
ListenerName = 'http'.
[RanchListenerSup | _] = 
    [Pid || {Name, Pid, _, _} <- supervisor:which_children(ranch_sup),
                                 Name =:= {ranch_listener_sup, ListenerName}].

% Stop listening.
ok = supervisor:terminate_child(RanchListenerSup, ranch_acceptors_sup).

% Start listening again.
% Assumes that you didn't use the 'socket' option, because it wants
% to call `Transport:listen/1` again.
{ok, _} = supervisor:restart_child(RanchListenerSup, ranch_acceptors_sup).
```

**Comment by ibizaman** [comment]
@rlipscombe I know it's been a while, but I tried what you said but it looks like the ranch listener is relaunched immediately.

**Comment by rlipscombe** [comment]
We've got the listener grafted into our supervision tree (we run ranch in "embedded" mode), so maybe that explains the difference?

**Comment by essen** [comment]
You can suspend listeners in the most recent commit. Please try it! Thanks.
