### ISSUE TITLE
ranch_conns_sup ignores socket controlling process error

### ISSUE THREAD

**Issue by fishcakez** [ninenines/ranch#96]
It is possible for `Transport:controlling_process/2` to return an error. The simplest example is when a `ranch_protocol` exits before `ranch_conns_sup` transfers ownership of the socket[1]. In this case `ranch_conns_sup` owns the socket and the socket is never closed as it is in passive mode.

[1] https://github.com/ninenines/ranch/blob/a41098520a9507e322752ee2738da34c79dee703/src/ranch_conns_sup.erl#L117

**Comment by essen** [comment]
Done in 02ff6533bbbc5dae95959c4979765d532d9e0af6. Not sure how to test it though. Thanks!
