### ISSUE TITLE
Support Server Name Indication (SNI)

### ISSUE THREAD

**Issue by fqj1994** [ninenines/ranch#98]
SNI is a TLS extension which allows clients to indicate the hostname while handshaking, making it possible for servers to present multiple certificates on a single IP address and port pair.
Erlang ssl module has hadded support to SNI, in ssl:ssloption() server_name_indication.
But I didn't see similar options in module ranch_ssl.
Please add support to it.
Thanks.

**Comment by essen** [comment]
Done in 0d5d855da3d0b2d508fae4258b125a3a5ab7b306. Thanks!
